<?php

namespace AppBundle\Repository;

/**
 * CarroceriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarroceriaRepository extends \Doctrine\ORM\EntityRepository
{
}
