<?php

namespace AppBundle\Repository;

/**
 * CasoInsumoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasoInsumoRepository extends \Doctrine\ORM\EntityRepository
{
}
