<?php

namespace AppBundle\Repository;

/**
 * CfgFestivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgFestivoRepository extends \Doctrine\ORM\EntityRepository
{
}
