<?php

namespace AppBundle\Repository;

/**
 * CfgLicenciaConduccionCategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgLicenciaConduccionCategoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
