<?php

namespace AppBundle\Repository;

/**
 * CfgModalidadTransporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgModalidadTransporteRepository extends \Doctrine\ORM\EntityRepository
{
}
