<?php

namespace AppBundle\Repository;

/**
 * CfgRadioAccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgRadioAccionRepository extends \Doctrine\ORM\EntityRepository
{
}
