<?php

namespace AppBundle\Repository;

/**
 * CfgSmlmvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgSmlmvRepository extends \Doctrine\ORM\EntityRepository
{
}
