<?php

namespace AppBundle\Repository;

/**
 * CfgTipoProcesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgTipoProcesoRepository extends \Doctrine\ORM\EntityRepository
{
}
