<?php

namespace AppBundle\Repository;

/**
 * CfgValorVehiculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgValorVehiculoRepository extends \Doctrine\ORM\EntityRepository
{
}
