<?php

namespace AppBundle\Repository;

/**
 * CiudadExtranjeraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CiudadExtranjeraRepository extends \Doctrine\ORM\EntityRepository
{
}
