<?php

namespace AppBundle\Repository;

/**
 * ComparendoInfraccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComparendoInfraccionRepository extends \Doctrine\ORM\EntityRepository
{
}
