<?php

namespace AppBundle\Repository;

/**
 * ConceptoParametroTramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptoParametroTramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
