<?php

namespace AppBundle\Repository;

/**
 * ConceptoParametroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptoParametroRepository extends \Doctrine\ORM\EntityRepository
{
}
