<?php

namespace AppBundle\Repository;

/**
 * ConceptoTramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptoTramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
