<?php

namespace AppBundle\Repository;

/**
 * CondicionIngresoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CondicionIngresoRepository extends \Doctrine\ORM\EntityRepository
{
}
