<?php

namespace AppBundle\Repository;

/**
 * ConsumiblesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsumiblesRepository extends \Doctrine\ORM\EntityRepository
{
}
