<?php

namespace AppBundle\Repository;

/**
 * CorrespondenciaDocumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorrespondenciaDocumentoRepository extends \Doctrine\ORM\EntityRepository
{
}
