<?php

namespace AppBundle\Repository;

/**
 * FacturaSustratoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturaSustratoRepository extends \Doctrine\ORM\EntityRepository
{
}
