<?php

namespace AppBundle\Repository;

/**
 * FasesDocumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FasesDocumentoRepository extends \Doctrine\ORM\EntityRepository
{
}
