<?php

namespace AppBundle\Repository;

/**
 * HistorialPrecioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistorialPrecioRepository extends \Doctrine\ORM\EntityRepository
{
}
