<?php

namespace AppBundle\Repository;

/**
 * InmovilizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InmovilizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
