<?php

namespace AppBundle\Repository;

/**
 * LicenciaConduccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicenciaConduccionRepository extends \Doctrine\ORM\EntityRepository
{
}
