<?php

namespace AppBundle\Repository;

/**
 * LimitacionDatosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LimitacionDatosRepository extends \Doctrine\ORM\EntityRepository
{
}
