<?php

namespace AppBundle\Repository;

/**
 * LiquidacionComparendoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiquidacionComparendoRepository extends \Doctrine\ORM\EntityRepository
{
}
