<?php

namespace AppBundle\Repository;

/**
 * MflInfraccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MflInfraccionRepository extends \Doctrine\ORM\EntityRepository
{
}
