<?php

namespace AppBundle\Repository;

/**
 * MflTipoRecaudoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MflTipoRecaudoRepository extends \Doctrine\ORM\EntityRepository
{
}
