<?php

namespace AppBundle\Repository;

/**
 * MgdPeticionarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MgdPeticionarioRepository extends \Doctrine\ORM\EntityRepository
{
}
