<?php

namespace AppBundle\Repository;

/**
 * MgdSeguimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MgdSeguimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
