<?php

namespace AppBundle\Repository;

/**
 * MparqCostoTrayectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MparqCostoTrayectoRepository extends \Doctrine\ORM\EntityRepository
{
}
