<?php

namespace AppBundle\Repository;

/**
 * MparqEntradaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MparqEntradaRepository extends \Doctrine\ORM\EntityRepository
{
}
