<?php

namespace AppBundle\Repository;

/**
 * MparqInmovilizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MparqInmovilizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
