<?php

namespace AppBundle\Repository;

/**
 * MpersonalHorarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MpersonalHorarioRepository extends \Doctrine\ORM\EntityRepository
{
}
