<?php

namespace AppBundle\Repository;

/**
 * MpersonalComparendoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MpersonalComparendoRepository extends \Doctrine\ORM\EntityRepository
{
}
