<?php

namespace AppBundle\Repository;

/**
 * MsvCaracterizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsvCaracterizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
