<?php

namespace AppBundle\Repository;

/**
 * MsvCategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsvCategoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
