<?php

namespace AppBundle\Repository;

/**
 * MsvCriterioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsvCriterioRepository extends \Doctrine\ORM\EntityRepository
{
}
