<?php

namespace AppBundle\Repository;

/**
 * MsvEvaluacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsvEvaluacionRepository extends \Doctrine\ORM\EntityRepository
{
}
