<?php

namespace AppBundle\Repository;

/**
 * MsvRevisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsvRevisionRepository extends \Doctrine\ORM\EntityRepository
{
}
