<?php

namespace AppBundle\Repository;

/**
 * MsvTCAsignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsvTCAsignacionRepository extends \Doctrine\ORM\EntityRepository
{
}
