<?php

namespace AppBundle\Repository;

/**
 * OrganismoTransitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganismoTransitoRepository extends \Doctrine\ORM\EntityRepository
{
}
