<?php

namespace AppBundle\Repository;

/**
 * OrigenRegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrigenRegistroRepository extends \Doctrine\ORM\EntityRepository
{
}
