<?php

namespace AppBundle\Repository;

/**
 * ParametrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametrRepository extends \Doctrine\ORM\EntityRepository
{
}
