<?php

namespace AppBundle\Repository;

/**
 * PropietarioVehiculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropietarioVehiculoRepository extends \Doctrine\ORM\EntityRepository
{
}
