<?php

namespace AppBundle\Repository;

/**
 * RepresentanteEmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepresentanteEmpresaRepository extends \Doctrine\ORM\EntityRepository
{
}
