<?php

namespace AppBundle\Repository;

/**
 * seguimientoEntregaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class seguimientoEntregaRepository extends \Doctrine\ORM\EntityRepository
{
}
