<?php

namespace AppBundle\Repository;

/**
 * SustratoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SustratoRepository extends \Doctrine\ORM\EntityRepository
{
}
