<?php

namespace AppBundle\Repository;

/**
 * TestigoComparendoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestigoComparendoRepository extends \Doctrine\ORM\EntityRepository
{
}
