<?php

namespace AppBundle\Repository;

/**
 * TipoSociedadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoSociedadRepository extends \Doctrine\ORM\EntityRepository
{
}
