<?php

namespace AppBundle\Repository;

/**
 * BodegaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoSenalRepository extends \Doctrine\ORM\EntityRepository
{
}
