<?php

namespace AppBundle\Repository;

/**
 * TipoRecaudoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoRecaudoRepository extends \Doctrine\ORM\EntityRepository
{
}
