<?php

namespace AppBundle\Repository;

/**
 * TipoDestinoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDestinoRepository extends \Doctrine\ORM\EntityRepository
{
}
