<?php

namespace AppBundle\Repository;

/**
 * TramiteTrasladoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TramiteTrasladoRepository extends \Doctrine\ORM\EntityRepository
{
}
