<?php

namespace AppBundle\Repository;

/**
 * TramiteAlertaPrendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TramiteAlertaPrendaRepository extends \Doctrine\ORM\EntityRepository
{
}
