<?php

namespace AppBundle\Repository;

/**
 * TramiteFacturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TramiteFacturaRepository extends \Doctrine\ORM\EntityRepository
{
    
}
