<?php

namespace AppBundle\Repository;

/**
 * VehiculoMedidaCautelarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculoMedidaCautelarRepository extends \Doctrine\ORM\EntityRepository
{
}
