<?php

namespace JHWEB\PersonalBundle\Repository;

/**
 * PnalCfgCdoConsecutivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PnalCfgCdoConsecutivoRepository extends \Doctrine\ORM\EntityRepository
{
}
