<?php

namespace JHWEB\PersonalBundle\Repository;

/**
 * PnalCfgTipoContratoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PnalCfgTipoContratoRepository extends \Doctrine\ORM\EntityRepository
{
}
