<?php

namespace JHWEB\PersonalBundle\Repository;

/**
 * PnalTalonarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PnalTalonarioRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastByFechaAndOrganismoTransito($idOrganismoTransito){ 
        $em = $this->getEntityManager();
        
        $dql = "SELECT pt
        FROM JHWEBPersonalBundle:PnalTalonario pt
        WHERE pt.fechaAsignacion = (
            SELECT MAX(pt2.fechaAsignacion)
            FROM JHWEBPersonalBundle:PnalTalonario pt2
            WHERE pt2.activo = true
            AND pt2.organismoTransito = :idOrganismoTransito
        ) 
        AND pt.activo = true
        AND pt.organismoTransito = :idOrganismoTransito";

        $consulta = $em->createQuery($dql)->setMaxResults(1);
		$consulta->setParameters(array(
            'idOrganismoTransito' => $idOrganismoTransito,
        ));

        return $consulta->getOneOrNullResult();
    }

    public function getMaximoByOrganismoTransito($idOrganismoTransito)
    { 
        $em = $this->getEntityManager();

        $dql = "SELECT MAX(pt.hasta) AS maximo
        FROM JHWEBPersonalBundle:PnalTalonario pt
        WHERE pt.organismoTransito = :idOrganismoTransito";

        $consulta = $em->createQuery($dql);
        $consulta->setParameters(array(
            'idOrganismoTransito' => $idOrganismoTransito,
        ));
        
        return $consulta->getOneOrNullResult();
    }

    //Obtiene la suma de cantidad disponible por organismo de transito
    public function getCantidadDisponibleByOrganismoTransito($idOrganismoTransito)
    {
        $em = $this->getEntityManager();

        $dql = "SELECT SUM(pt.cantidadDisponible) AS total
            FROM JHWEBPersonalBundle:PnalTalonario pt
            WHERE pt.organismoTransito = :idOrganismoTransito
            AND pt.activo = true";
            
        $consulta = $em->createQuery($dql);

        $consulta->setParameter('idOrganismoTransito', $idOrganismoTransito);
        
        return $consulta->getOneOrNullResult();
    }
}
