<?php

namespace JHWEB\PersonalBundle\Repository;

/**
 * PnalAsignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PnalAsignacionRepository extends \Doctrine\ORM\EntityRepository
{
    //Obtiene el numero maximo de asignaciones por año
    public function getMaximo($anio)
    {
        $em = $this->getEntityManager();
        
        $dql = "SELECT MAX(a.consecutivo) AS maximo
            FROM JHWEBPersonalBundle:PnalAsignacion a
            WHERE YEAR(a.fecha) = :ANIO";

        $consulta = $em->createQuery($dql);
        $consulta->setParameter('ANIO', $anio);

        return $consulta->getOneOrNullResult();
    }

    //Obtiene la lista de documentos por peticionario
    public function getFuncionariosByCargo($params, $cargo){   
        $em = $this->getEntityManager();

    	$dql = "SELECT f
        FROM JHWEBPersonalBundle:PnalFuncionario f, 
        JHWEBUsuarioBundle:UserCiudadano c,
        UsuarioBundle:Usuario u
        WHERE u.id = c.usuario
        AND c.id = f.ciudadano
        AND (c.primerNombre = :parametro 
        OR c.segundoNombre = :parametro 
        OR c.primerApellido = :parametro 
        OR c.segundoApellido = :parametro 
        OR f.numeroPlaca = :parametro)
        AND f.cargo = :cargo";

        $consulta = $em->createQuery($dql);
        $consulta->setParameters(array(
            'parametro' => $params->parametro,
            'cargo' => $cargo,
        ));


        return $consulta->getResult();
    }

    public function getLastByFechaAndOrganismoTransito($idOrganismoTransito){ 
        $em = $this->getEntityManager();
        
        $dql = "SELECT pa
        FROM JHWEBPersonalBundle:PnalAsignacion pa
        WHERE pa.fecha = (
            SELECT MAX(pa2.fecha)
            FROM JHWEBPersonalBundle:PnalAsignacion pa2
            WHERE pa2.activo = true
            AND pa2.organismoTransito = :idOrganismoTransito
        ) 
        AND pa.organismoTransito = :idOrganismoTransito
        AND pa.activo = true";

        $consulta = $em->createQuery($dql)->setMaxResults(1);

        $consulta->setParameter('idOrganismoTransito', $idOrganismoTransito);
		
        return $consulta->getOneOrNullResult();
    }

    //Obtiene la suma de cantidad disponible por organismo de transito
    public function getCantidadDisponibleByOrganismoTransito($idOrganismoTransito)
    {
        $em = $this->getEntityManager();

        $dql = "SELECT SUM(pa.cantidadDisponible) AS total
            FROM JHWEBPersonalBundle:PnalAsignacion pa
            WHERE pa.organismoTransito = :idOrganismoTransito
            AND pa.activo = true";
            
        $consulta = $em->createQuery($dql);

        $consulta->setParameter('idOrganismoTransito', $idOrganismoTransito);
        
        return $consulta->getOneOrNullResult();
    }

    public function getMaximoByOrganismoTransito($idOrganismoTransito)
    { 
        $em = $this->getEntityManager();

        $dql = "SELECT MAX(pt.hasta) AS maximo
        FROM JHWEBPersonalBundle:PnalAsignacion pt
        WHERE pt.organismoTransito = :idOrganismoTransito";

        $consulta = $em->createQuery($dql);
        $consulta->setParameters(array(
            'idOrganismoTransito' => $idOrganismoTransito,
        ));
        
        return $consulta->getOneOrNullResult();
    }
}
