<?php

namespace JHWEB\PersonalBundle\Repository;

/**
 * PnalAsignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PnalAsignacionRepository extends \Doctrine\ORM\EntityRepository
{
    //Obtiene la lista de documentos por peticionario
    public function getFuncionariosByCargo($params, $cargo){   
        $em = $this->getEntityManager();

    	$dql = "SELECT f
        FROM JHWEBPersonalBundle:PnalFuncionario f, 
        JHWEBUsuarioBundle:UserCiudadano c,
        UsuarioBundle:Usuario u
        WHERE u.id = c.usuario
        AND c.id = f.ciudadano
        AND (c.primerNombre = :parametro 
        OR c.segundoNombre = :parametro 
        OR c.primerApellido = :parametro 
        OR c.segundoApellido = :parametro 
        OR f.numeroPlaca = :parametro)
        AND f.cargo = :cargo";

        $consulta = $em->createQuery($dql);
        $consulta->setParameters(array(
            'parametro' => $params->parametro,
            'cargo' => $cargo,
        ));


        return $consulta->getResult();
    }
}
