<?php

namespace JHWEB\PersonalBundle\Repository;

/**
 * PnalCfgTipoNombramientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PnalCfgTipoNombramientoRepository extends \Doctrine\ORM\EntityRepository
{
}
