<?php

namespace JHWEB\PersonalBundle\Repository;

/**
 * PnalHorarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PnalHorarioRepository extends \Doctrine\ORM\EntityRepository
{
}
