<?php

namespace JHWEB\PersonalBundle\Repository;

/**
 * PnalSuspensionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PnalSuspensionRepository extends \Doctrine\ORM\EntityRepository
{
}
