<?php

namespace JHWEB\PersonalBundle\Repository;

/**
 * PnalFuncionarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PnalFuncionarioRepository extends \Doctrine\ORM\EntityRepository
{
}
