<?php

namespace JHWEB\PersonalBundle\Repository;

/**
 * PnalCfgCargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PnalCfgCargoRepository extends \Doctrine\ORM\EntityRepository
{
}
