<?php

namespace JHWEB\PersonalBundle\Repository;

/**
 * PnalAsignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PnalAsignacionRepository extends \Doctrine\ORM\EntityRepository
{
}
