<?php

namespace JHWEB\PersonalBundle\Repository;

/**
 * PnalTalonarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PnalTalonarioRepository extends \Doctrine\ORM\EntityRepository
{
}
