<?php

namespace JHWEB\PersonalBundle\Repository;

/**
 * PnalProrogaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PnalProrogaRepository extends \Doctrine\ORM\EntityRepository
{
}
