<?php

namespace JHWEB\PersonalBundle\Repository;

/**
 * PnalCfgCdoBodegaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PnalCfgCdoBodegaRepository extends \Doctrine\ORM\EntityRepository
{
    //Obtiene el total de consecutivos disponibles en bodedga
    public function getTotalDisponible()
    { 
        $em = $this->getEntityManager();
        $dql = "SELECT SUM(b.cantidadDisponible) AS total
            FROM JHWEBPersonalBundle:PnalCfgCdoBodega b
            WHERE b.activo = true
            AND b.estado = 'DISPONIBLE'";

        $consulta = $em->createQuery($dql);
        
        return $consulta->getOneOrNullResult();
    }
}
