<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroAmotizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroAmotizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
