<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroAcuerdoPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroAcuerdoPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
