<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroAmortizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroAmortizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
