<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroClaveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroClaveRepository extends \Doctrine\ORM\EntityRepository
{
}
