<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroCfgTipoRecaudoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroCfgTipoRecaudoRepository extends \Doctrine\ORM\EntityRepository
{
}
