<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroFacturaComparendoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroFacturaComparendoRepository extends \Doctrine\ORM\EntityRepository
{
}
