<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroFacTramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroFacTramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
