<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroFacInsumoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroFacInsumoRepository extends \Doctrine\ORM\EntityRepository
{
}
