<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroFacExcedenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroFacExcedenteRepository extends \Doctrine\ORM\EntityRepository
{
}
