<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroFacRetefuenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroFacRetefuenteRepository extends \Doctrine\ORM\EntityRepository
{
    //Obtiene la suma de total de retenciones por factura
    public function getTotalByFactura($idFactura)
    {
        $em = $this->getEntityManager();

        $dql = "SELECT SUM(r.retencion) AS total
            FROM JHWEBFinancieroBundle:FroFacRetefuente r
            WHERE r.factura = :idFactura
            AND r.activo = true";
            
        $consulta = $em->createQuery($dql);

        $consulta->setParameter('idFactura', $idFactura);
        
        return $consulta->getOneOrNullResult();
    }
}
