<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroFacComparendoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroFacComparendoRepository extends \Doctrine\ORM\EntityRepository
{
}
