<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroFacturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroFacturaRepository extends \Doctrine\ORM\EntityRepository
{
}
