<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroFacParqueaderoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroFacParqueaderoRepository extends \Doctrine\ORM\EntityRepository
{
}
