<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroFacArchivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroFacArchivoRepository extends \Doctrine\ORM\EntityRepository
{
}
