<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroFacturaTramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroFacturaTramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
