<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroFacRetefuenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroFacRetefuenteRepository extends \Doctrine\ORM\EntityRepository
{
}
