<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroFacTransferenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroFacTransferenciaRepository extends \Doctrine\ORM\EntityRepository
{
    //Obtiene todas las transferencias entre fechas
    public function getReportTransfer($fechaInicial, $fechaFinal)
    {
        $em = $this->getEntityManager();
        
        $dql = "SELECT t
        FROM JHWEBFinancieroBundle:FroFacTransferencia t,
        JHWEBFinancieroBundle:FroFactura f
        WHERE t.factura = f.id
        AND t.fecha BETWEEN :fechaInicial AND :fechaFinal
        ORDER BY t.fecha, t.hora ASC";

        $consulta = $em->createQuery($dql);

        $consulta->setParameters(array(
	        'fechaInicial' => $fechaInicial,
	        'fechaFinal' => $fechaFinal,
	    ));

        return $consulta->getResult();
    }
}
