<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroInfraccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroInfraccionRepository extends \Doctrine\ORM\EntityRepository
{
}
