<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroInfrCfgCategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroInfrCfgCategoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
