<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroRecaudoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroRecaudoRepository extends \Doctrine\ORM\EntityRepository
{
}
