<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroReporteIngresosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroReporteIngresosRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTramitesByFecha($fechaInicioDatetime, $fechaFinDatetime, $organismoTransito) {
        
        $em = $this->getEntityManager();

        $dql = "SELECT fts
            FROM JHWEBFinancieroBundle:FroTrteSolicitud fts
            WHERE fts.organismoTransito = :organismoTransito
            AND fts.fecha BETWEEN :fechaInicio AND :fechaFin";

        $consulta = $em->createQuery($dql);
        
        $consulta->setParameters(array(
            'organismoTransito' => $organismoTransito, 
            'fechaInicio' => $fechaInicioDatetime,
            'fechaFin' => $fechaFinDatetime,
        ));

        return $consulta->getResult();
    }
}
