<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroReporteIngresosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroReporteIngresosRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTramitesByFecha($params) {
        
        $em = $this->getEntityManager();

        $fechaInicio = new \Datetime($params->fechaDesde);
        $fechaFin = new \Datetime($params->fechaHasta);
        $organismoTransito = $em->getRepository('JHWEBConfigBundle:CfgOrganismoTransito')->find($params->idOrganismoTransito);
        $tipoRecaudo= $em->getRepository('JHWEBFinancieroBundle:FroCfgTipoRecaudo')->find($params->idTipoRecaudo);

        $dqlPagadas = "SELECT ft
            FROM JHWEBFinancieroBundle:FroTramite ft, JHWEBFinancieroBundle:FroFactura ff, 
            JHWEBConfigBundle:CfgOrganismoTransito ot, JHWEBFinancieroBundle:FroCfgTipoRecaudo tr,
            JHWEBFinancieroBundle:FroTrtePrecio ftp, JHWEBFinancieroBundle:FroFacTramite  fft,
            JHWEBFinancieroBundle:FroTrteConcepto ftc
            WHERE ft.id = ftp.tramite
            AND ftc.precio = ftp.id
            AND fft.precio = ftp.id
            AND ff.tipoRecaudo = :tipoRecaudo 
            AND ff.organismoTransito = :organismoTransito
            AND ff.fechaPago BETWEEN :fechaInicio AND :fechaFin
            AND ff.estado = 'PAGADA'";

        $dqlNoPagadas = "SELECT ft
            FROM JHWEBFinancieroBundle:FroTramite ft, JHWEBFinancieroBundle:FroFactura ff, 
            JHWEBConfigBundle:CfgOrganismoTransito ot, JHWEBFinancieroBundle:FroCfgTipoRecaudo tr,
            JHWEBFinancieroBundle:FroTrtePrecio ftp, JHWEBFinancieroBundle:FroFacTramite  fft,
            JHWEBFinancieroBundle:FroTrteConcepto ftc
            WHERE ft.id = ftp.tramite
            AND ftc.precio = ftp.id
            AND fft.precio = ftp.id
            AND ff.tipoRecaudo = :tipoRecaudo 
            AND ff.organismoTransito = :organismoTransito
            AND ff.fechaPago BETWEEN :fechaInicio AND :fechaFin";

        $consultaPagadas = $em->createQuery($dqlPagadas);
        $consultaNoPagadas = $em->createQuery($dqlNoPagadas);
        
        
        $consultaPagadas->setParameters(array(
            'organismoTransito' => $organismoTransito, 
            'tipoRecaudo' => $tipoRecaudo,
            'fechaInicio' => $fechaInicio,
            'fechaFin' => $fechaFin,
        ));
        
        $consultaNoPagadas->setParameters(array(
            'organismoTransito' => $organismoTransito, 
            'tipoRecaudo' => $tipoRecaudo,
            'fechaInicio' => $fechaInicio,
            'fechaFin' => $fechaFin,
        ));
        
        $data[] = array(
            'pagadas' => $consultaPagadas->getResult(),
            'noPagadas' => $consultaNoPagadas->getResult(),
        );

        return $data;
    }
}
