<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroReporteIngresosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroReporteIngresosRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTramitesDiario($fecha, $idOrganismoTransito) {
        $em = $this->getEntityManager();

        $dql = "SELECT fts
            FROM JHWEBFinancieroBundle:FroTrteSolicitud fts,
            JHWEBFinancieroBundle:FroFactura ff,
            JHWEBFinancieroBundle:FroFacTramite fft
            WHERE fts.organismoTransito = :idOrganismoTransito 
            AND fts.tramiteFactura = fft.id
            AND fft.factura = ff.id
            AND ff.fechaPago = :fecha";

        $consulta = $em->createQuery($dql);
        
        $consulta->setParameters(array(
            'idOrganismoTransito' => $idOrganismoTransito, 
            'fecha' => $fecha,
        ));

        return $consulta->getResult();
    }

    public function findTramitesMensual($fechaInicioDatetime, $fechaFinDatetime, $idOrganismoTransito) {
        $em = $this->getEntityManager();

        $dql = "SELECT fts
            FROM JHWEBFinancieroBundle:FroTrteSolicitud fts,
            JHWEBFinancieroBundle:FroFactura ff,
            JHWEBFinancieroBundle:FroFacTramite fft
            WHERE fts.organismoTransito = :idOrganismoTransito 
            AND fts.tramiteFactura = fft.id
            AND fft.factura = ff.id
            AND ff.fechaPago BETWEEN :fechaInicio AND :fechaFin";

        $consulta = $em->createQuery($dql);
        
        $consulta->setParameters(array(
            'idOrganismoTransito' => $idOrganismoTransito, 
            'fechaInicio' => $fechaInicioDatetime,
            'fechaFin' => $fechaFinDatetime,
        ));

        return $consulta->getResult();
    }

    public function getByName($idConcepto, $idPrecio) {
        $em = $this->getEntityManager();

        $dql = "SELECT COUNT(ftc.id)
            FROM JHWEBFinancieroBundle:FroTrteConcepto ftc
            WHERE ftc.concepto = :idConcepto
            AND ftc.precio = :idPrecio";

        $consulta = $em->createQuery($dql);
        
        $consulta->setParameters(array(
            'idConcepto' => $idConcepto, 
            'idPrecio' => $idPrecio, 
        ));

        return $consulta->getOneOrNullResult();
    }

    public function getTramiteByName($idTramite) {
        $em = $this->getEntityManager();

        $dql = "SELECT COUNT(ftp.id)
            FROM JHWEBFinancieroBundle:FroTrtePrecio ftp
            WHERE ftp.tramite = :idTramite";

        $consulta = $em->createQuery($dql);
        
        $consulta->setParameters(array(
            'idTramite' => $idTramite, 
        ));

        return $consulta->getOneOrNullResult();
    }

    public function getSustratosByName($idFactura) {
        $em = $this->getEntityManager();

        $dql = "SELECT COUNT(ii.tipo)
            FROM JHWEBInsumoBundle:ImoInsumo ii
            WHERE ii.factura = :idFactura";

        $consulta = $em->createQuery($dql);
        
        $consulta->setParameters(array(
            'idFactura' => $idFactura, 
        ));

        return $consulta->getOneOrNullResult();
    }
    /*  =============== para infracciones ================= */

    public function getInfraccionesByFecha($fechaInicioDatetime, $fechaFinDatetime, $idOrganismoTransito) {
        $em = $this->getEntityManager();

        $dql = "SELECT ccc
            FROM JHWEBContravencionalBundle:CvCdoComparendo ccc,
            WHERE ccc.organismoTransito = :idOrganismoTransito 
            AND ccc.fecha BETWEEN :fechaInicio AND :fechaFin";

        $consulta = $em->createQuery($dql);
        
        $consulta->setParameters(array(
            'idOrganismoTransito' => $idOrganismoTransito, 
            'fechaInicio' => $fechaInicioDatetime,
            'fechaFin' => $fechaFinDatetime,
        ));

        return $consulta->getResult();
    }
}
