<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroTrteTramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroTrteTramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
