<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroTrteCfgConceptoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroTrteCfgConceptoRepository extends \Doctrine\ORM\EntityRepository
{
}
