<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroTrtePrecioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroTrtePrecioRepository extends \Doctrine\ORM\EntityRepository
{
}
