<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroTrteConceptoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroTrteConceptoRepository extends \Doctrine\ORM\EntityRepository
{
}
