<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroTramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroTramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
