<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroTrteCfgCuentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroTrteCfgCuentaRepository extends \Doctrine\ORM\EntityRepository
{
}
