<?php

namespace JHWEB\FinancieroBundle\Repository;

/**
 * FroTrteCarpetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FroTrteCarpetaRepository extends \Doctrine\ORM\EntityRepository
{
}
