<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserLicenciaTransitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLicenciaTransitoRepository extends \Doctrine\ORM\EntityRepository
{
}
