<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserMedidaCautelarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMedidaCautelarRepository extends \Doctrine\ORM\EntityRepository
{
}
