<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserLicenciaConduccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLicenciaConduccionRepository extends \Doctrine\ORM\EntityRepository
{
}
