<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserLcCfgCategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLcCfgCategoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
