<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserLicenciaConduccionRestriccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLicenciaConduccionRestriccionRepository extends \Doctrine\ORM\EntityRepository
{
}
