<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserCfgRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCfgRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
