<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserCfgGeneroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCfgGeneroRepository extends \Doctrine\ORM\EntityRepository
{
}
