<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserCfgGrupoSanguineoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCfgGrupoSanguineoRepository extends \Doctrine\ORM\EntityRepository
{
}
