<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserLcProhibicionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLcProhibicionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFecha($fechaInicial, $fechaFinal)
    { 
        $em = $this->getEntityManager();
 
        $dql = "SELECT up
        FROM JHWEBUsuarioBundle:UserLcProhibicion up
        WHERE up.fechaInicio BETWEEN :fechaInicial AND :fechaFinal";

        $consulta = $em->createQuery($dql); 
        $consulta->setParameters(array(
            'fechaInicial' => $fechaInicial,
            'fechaFinal' => $fechaFinal,
        ));

        return $consulta->getResult();
    }
}
