<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserCfgEmpresaTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCfgEmpresaTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
