<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserCiudadanoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCiudadanoRepository extends \Doctrine\ORM\EntityRepository
{
	public function getByFilter($params){
        $em = $this->getEntityManager();

        switch ($params->tipoFiltro) {
            case 1:
                $dql = "SELECT c
                FROM JHWEBUsuarioBundle:UserCiudadano c,
                UsuarioBundle:Usuario u
                WHERE c.identificacion = :identificacion
                AND c.usuario = u.id
                ORDER BY c.primerNombre, c.primerApellido ASC";

                $consulta = $em->createQuery($dql);
                $consulta->setParameters(array(
                    'identificacion' => $params->filtro,
                ));
                break;

            case 2:
                $dql = "SELECT c
                FROM JHWEBUsuarioBundle:UserCiudadano c,
                UsuarioBundle:Usuario u
                WHERE c.usuario = u.id
                AND (c.primerNombre LIKE :nombres OR c.segundoNombre LIKE :nombres
                OR c.primerApellido LIKE :apellidos OR c.segundoApellido LIKE :apellidos)
                ORDER BY c.primerNombre, c.primerApellido ASC";

                $consulta = $em->createQuery($dql);
                $consulta->setParameters(array(
                    'nombres' => '%'.$params->filtro.'%',
                    'apellidos' => '%'.$params->filtro.'%',
                ));
                break;
        }

        return $consulta->getResult();
    }
}
