<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserCfgTipoIdentificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCfgTipoIdentificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
