<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserLcRestriccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLcRestriccionRepository extends \Doctrine\ORM\EntityRepository
{
}
