<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserEmpresaTransporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEmpresaTransporteRepository extends \Doctrine\ORM\EntityRepository
{
}
