<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserEmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEmpresaRepository extends \Doctrine\ORM\EntityRepository
{
	//Obtiene la empresa segun el NIT o Nombre
    public function getByNitOrNombre($parametro){
        $em = $this->getEntityManager();

        $condicion = null;

        $sql = " SELECT e
        FROM JHWEBUsuarioBundle:UserEmpresa e
        WHERE (e.nombre = :nombre)"; 
        
        if($parametro->parametro2){
            $condicion .= "OR e.nit = '" .$parametro->parametro2."'";
        }
        
        if($condicion){
            $sql .= $condicion;
        } 

        $consulta = $em->createQuery($sql);
        $consulta->setParameters(
        	array('nombre' => $parametro->parametro)
        );

        return $consulta->getOneOrNullResult();
    }
}
