<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserEmpresaSucursalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEmpresaSucursalRepository extends \Doctrine\ORM\EntityRepository
{
}
