<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserMedidaCautelarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMedidaCautelarRepository extends \Doctrine\ORM\EntityRepository
{
    //Obtiene medidas cautelares según el filtro de búsqueda
    public function getByFechasForFile($fechaDesde, $fechaHasta)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT umc as medidaCautelar, uc.identificacion, vcp.numero as placa
            FROM JHWEBUsuarioBundle:UserMedidaCautelar umc, 
            JHWEBUsuarioBundle:UserCiudadano uc,
            JHWEBVehiculoBundle:VhloPropietario vp,
            JHWEBVehiculoBundle:VhloVehiculo v,
            JHWEBVehiculoBundle:VhloCfgPlaca vcp

            WHERE umc.fechaInicio BETWEEN :fechaDesde AND :fechaHasta
            AND umc.ciudadano = uc.id
            AND vp.ciudadano = uc.id
            AND vp.vehiculo = v.id
            AND v.placa = vcp.id
            AND vp.activo = 1";

        $consulta = $em->createQuery($dql);
    
        $consulta->setParameters(array(
            'fechaDesde' => $fechaDesde,
            'fechaHasta' => $fechaHasta
        ));
        
        return $consulta->getResult();
    }
}
