<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserCfgEmpresaTipoSociedadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCfgEmpresaTipoSociedadRepository extends \Doctrine\ORM\EntityRepository
{
}
