<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserEmpresaRepresentanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEmpresaRepresentanteRepository extends \Doctrine\ORM\EntityRepository
{
}
