<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserCfgRoleMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCfgRoleMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
