<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserCfgEmpresaServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCfgEmpresaServicioRepository extends \Doctrine\ORM\EntityRepository
{
}
