<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserCfgGrupoEtnicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCfgGrupoEtnicoRepository extends \Doctrine\ORM\EntityRepository
{
}
