<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserUsuarioMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserUsuarioMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
