<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserRestriccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRestriccionRepository extends \Doctrine\ORM\EntityRepository
{
}
