<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserEmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEmpresaRepository extends \Doctrine\ORM\EntityRepository
{
	//Obtiene la empresa segun el NIT o Nombre
    public function getByNitOrNombre($parametro){
        $em = $this->getEntityManager();

        $condicion = null;

        $sql = " SELECT e
        FROM JHWEBUsuarioBundle:UserEmpresa e
        WHERE (e.nombre = :nombre)"; 
        
        if($parametro->parametro2){
            $condicion .= "OR e.nit = '" .$parametro->parametro2."'";
        }
        
        if($condicion){
            $sql .= $condicion;
        } 

        $consulta = $em->createQuery($sql);
        $consulta->setParameters(
        	array('nombre' => $parametro->parametro)
        );

        return $consulta->getOneOrNullResult();
    }

    public function getByFilter($params){
        $em = $this->getEntityManager();

        switch ($params->tipoFiltro) {
            case 1:
                $dql = "SELECT e
                FROM JHWEBUsuarioBundle:UserEmpresa e
                WHERE e.nit = :nit
                ORDER BY e.nombre ASC";

                $consulta = $em->createQuery($dql);
                $consulta->setParameters(array(
                    'nit' => $params->filtro,
                ));
                break;

            case 2:
                $dql = "SELECT e
                FROM JHWEBUsuarioBundle:UserEmpresa e
                WHERE e.nombre LIKE :nombre
                ORDER BY e.nombre ASC";

                $consulta = $em->createQuery($dql);
                $consulta->setParameters(array(
                    'nombre' => '%'.$params->filtro.'%',
                ));
                break;
        }

        return $consulta->getResult();
    }
}
