<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserLicenciaTrancitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLicenciaTrancitoRepository extends \Doctrine\ORM\EntityRepository
{
}
