<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserLcCfgRestriccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLcCfgRestriccionRepository extends \Doctrine\ORM\EntityRepository
{
}
