<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserCfgTipoMedidaCautelarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCfgTipoMedidaCautelarRepository extends \Doctrine\ORM\EntityRepository
{
}
