<?php

namespace JHWEB\UsuarioBundle\Repository;

/**
 * UserLcProhibicionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLcProhibicionRepository extends \Doctrine\ORM\EntityRepository
{
}
