<?php

namespace JHWEB\InsumoBundle\Repository;

/**
 * ImoAsignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImoAsignacionRepository extends \Doctrine\ORM\EntityRepository
{
}
