<?php

namespace JHWEB\InsumoBundle\Repository;

/**
 * ImoCfgTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImoCfgTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
