<?php

namespace JHWEB\InsumoBundle\Repository;

/**
 * ImoCfgValorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImoCfgValorRepository extends \Doctrine\ORM\EntityRepository
{
}
