<?php

namespace JHWEB\InsumoBundle\Repository;

/**
 * ImoLoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImoLoteRepository extends \Doctrine\ORM\EntityRepository
{
}
