<?php

namespace JHWEB\InsumoBundle\Repository;

/**
 * ImoLoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImoLoteRepository extends \Doctrine\ORM\EntityRepository
{

    public function getMax($imoCfgTipo)
    { 
        $em = $this->getEntityManager();
        $dql = "SELECT MAX(l.rangoFin) AS maximo
        FROM JHWEBInsumoBundle:ImoLote l, JHWEBInsumoBundle:ImoCfgTipo t
        WHERE l.tipoInsumo = t.id
        AND l.tipoInsumo = :imoTipo";
        $consulta = $em->createQuery($dql);
        $consulta->setParameters(array(
            'imoTipo' => $imoCfgTipo,
        ));
        return $consulta->getOneOrNullResult();
    }

    public function getMaxActa() 
    { 
        $em = $this->getEntityManager();

        $dql = "SELECT MAX(l.actaEntrega) AS maximo
        FROM JHWEBInsumoBundle:ImoInsumo l";
        $consulta = $em->createQuery($dql);
        return $consulta->getOneOrNullResult();
    }

    public function getByFechasAndTipo($fechaInicial, $fechaFinal, $tipo)
    {  
        $em = $this->getEntityManager();
        $dql = "SELECT l
            FROM JHWEBInsumoBundle:ImoLote l,
            JHWEBInsumoBundle:ImoCfgTipo t
            WHERE l.tipo = :tipo
            AND l.tipoInsumo = t.id
            AND l.fecha BETWEEN :fechaInicial AND :fechaFinal";

            $consulta = $em->createQuery($dql);
            $consulta->setParameters(array(
                'tipo' => $tipo,
                'fechaInicial' => $fechaInicial,
                'fechaFinal' => $fechaFinal,
            ));

            return $consulta->getResult();
    }

    public function getTotalesByTipo($fechaInicial, $fechaFinal, $tipo)
    { 
        $em = $this->getEntityManager();

        $dql = "SELECT SUM(il.cantidad) AS cantidad, it.nombre
        FROM JHWEBInsumoBundle:ImoLote il,
        JHWEBInsumoBundle:ImoCfgTipo it
        WHERE il.tipoInsumo = it.id
        AND il.tipo = :tipo
        AND il.fecha BETWEEN :fechaInicial AND :fechaFinal
        GROUP BY il.tipoInsumo";

        $consulta = $em->createQuery($dql);
        $consulta->setParameters(array(
            'tipo' => $tipo,
            'fechaInicial' => $fechaInicial,
            'fechaFinal' => $fechaFinal,
        ));

        return $consulta->getResult();
    }

    //Obtiene todos los lotes segun el tipo de insumo por organismo de transito y modulo
    public function getByOrganismoTransitoAndModulo($idModulo, $idOrganismoTransito, $tipoInsumo)
    { 
        $dql = "SELECT l
        FROM JHWEBInsumoBundle:ImoLote l,
        JHWEBInsumoBundle:ImoCfgTipo t
        WHERE l.tipo = :tipoInsumo
        AND l.tipoInsumo = t.id
        AND t.id = :idModulo
        AND l.sedeOperativa = :idOrganismoTransito
        AND estado = 'REGISTRADO'";

        $consulta = $em->createQuery($dql);
        $consulta->setParameters(array(
            'tipoInsumo' => $tipoInsumo,
            'idModulo' => $idModulo,
            'idOrganismoTransito' => $idOrganismoTransito,
        ));

        return $consulta->getResult();
    }

    public function getTotalByTipoInsumoAndModulo($estado, $tipoInsumo, $idModulo)
    {  
        $em = $this->getEntityManager();

        $dql = "SELECT SUM(il.cantidad) AS cantidad, 
        it.nombre, il.id AS idLote, it.id AS idTipoInsumo
        FROM JHWEBInsumoBundle:ImoLote il,
        JHWEBInsumoBundle:ImoCfgTipo it
        WHERE il.tipoInsumo = :tipoInsumo
        AND il.tipoInsumo = it.id
        AND il.estado = :estado7
        AND it.modulo = :idModulo";

        $consulta = $em->createQuery($dql);

        $consulta->setParameters(array(
            'estado' => $estado, 
            'tipoInsumo' => $tipoInsumo,
            'idModulo' => $idModulo,
        ));

        return $consulta->getOneOrNullResult();
    }
}
 