<?php

namespace JHWEB\InsumoBundle\Repository;

/**
 * ImoTrazabilidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImoTrazabilidadRepository extends \Doctrine\ORM\EntityRepository
{
}
