<?php

namespace AppBundle\Repository;

/**
 * AgenteTransitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenteTransitoRepository extends \Doctrine\ORM\EntityRepository
{
}
