<?php

namespace AppBundle\Repository;

/**
 * Campo_TablaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Campo_TablaRepository extends \Doctrine\ORM\EntityRepository
{
}
