<?php

namespace AppBundle\Repository;

/**
 * CampoTablaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampoTablaRepository extends \Doctrine\ORM\EntityRepository
{
}
