<?php

namespace AppBundle\Repository;

/**
 * CampoTramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampoTramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
