<?php

namespace AppBundle\Repository;

/**
 * CargaPasajeroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CargaPasajeroRepository extends \Doctrine\ORM\EntityRepository
{
}
