<?php

namespace AppBundle\Repository;

/**
 * CasoTramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasoTramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
