<?php

namespace AppBundle\Repository;

/**
 * Caso_TramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Caso_TramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
