<?php

namespace AppBundle\Repository;

/**
 * CfgAsignacionPlacaSedeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgAsignacionPlacaSedeRepository extends \Doctrine\ORM\EntityRepository
{
}
