<?php

namespace AppBundle\Repository;

/**
 * CfgBodegaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgBodegaRepository extends \Doctrine\ORM\EntityRepository
{
}
