<?php

namespace AppBundle\Repository;

/**
 * CfgChoqueConRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgChoqueConRepository extends \Doctrine\ORM\EntityRepository
{
}
