<?php

namespace AppBundle\Repository;

/**
 * CfgCargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgCargoRepository extends \Doctrine\ORM\EntityRepository
{
}
