<?php

namespace AppBundle\Repository;

/**
 * CfgClaseAccidenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgClaseAccidenteRepository extends \Doctrine\ORM\EntityRepository
{
}
