<?php

namespace AppBundle\Repository;

/**
 * CfgCausalLimitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgCausalLimitacionRepository extends \Doctrine\ORM\EntityRepository
{
}
