<?php

namespace AppBundle\Repository;

/**
 * CfgComparendoEstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgComparendoEstadoRepository extends \Doctrine\ORM\EntityRepository
{
}
