<?php

namespace AppBundle\Repository;

/**
 * CfgEmpresaGpsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgEmpresaGpsRepository extends \Doctrine\ORM\EntityRepository
{
}
