<?php

namespace AppBundle\Repository;

/**
 * CfgFormatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgFormatoRepository extends \Doctrine\ORM\EntityRepository
{
}
