<?php

namespace AppBundle\Repository;

/**
 * CfgGravedadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgGravedadRepository extends \Doctrine\ORM\EntityRepository
{
}
