<?php

namespace AppBundle\Repository;

/**
 * CfgInventarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgInventarioRepository extends \Doctrine\ORM\EntityRepository
{
}
