<?php

namespace AppBundle\Repository;

/**
 * CfgLimitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgLimitacionRepository extends \Doctrine\ORM\EntityRepository
{
}
