<?php

namespace AppBundle\Repository;

/**
 * CfgOrigenRegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgOrigenRegistroRepository extends \Doctrine\ORM\EntityRepository
{
}
