<?php

namespace AppBundle\Repository;

/**
 * CfgObjetoFijoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgObjetoFijoRepository extends \Doctrine\ORM\EntityRepository
{
}
