<?php

namespace AppBundle\Repository;

/**
 * CfgPlacaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgPlacaRepository extends \Doctrine\ORM\EntityRepository
{
}
