<?php

namespace AppBundle\Repository;

/**
 * CfgTipoInfractorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgTipoInfractorRepository extends \Doctrine\ORM\EntityRepository
{
}
