<?php

namespace AppBundle\Repository;

/**
 * CfgTipoEstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgTipoEstadoRepository extends \Doctrine\ORM\EntityRepository
{
}
