<?php

namespace AppBundle\Repository;

/**
 * CfgTipoClaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgTipoClaseRepository extends \Doctrine\ORM\EntityRepository
{
}
