<?php

namespace AppBundle\Repository;

/**
 * CfgTipoDestinoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgTipoDestinoRepository extends \Doctrine\ORM\EntityRepository
{
}
