<?php

namespace AppBundle\Repository;

/**
 * CfgTipoColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgTipoColorRepository extends \Doctrine\ORM\EntityRepository
{
}
