<?php

namespace AppBundle\Repository;

/**
 * CfgTipoVehiculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgTipoVehiculoRepository extends \Doctrine\ORM\EntityRepository
{
}
