<?php

namespace AppBundle\Repository;

/**
 * CfgTipoAlertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgTipoAlertaRepository extends \Doctrine\ORM\EntityRepository
{
}
