<?php

namespace AppBundle\Repository;

/**
 * Ciudadano_vehiculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ciudadano_vehiculoRepository extends \Doctrine\ORM\EntityRepository
{
}
