<?php

namespace AppBundle\Repository;

/**
 * CiudadanoVehiculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CiudadanoVehiculoRepository extends \Doctrine\ORM\EntityRepository
{
}
