<?php

namespace AppBundle\Repository;

/**
 * CualquieraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CualquieraRepository extends \Doctrine\ORM\EntityRepository
{
}
