<?php

namespace AppBundle\Repository;

/**
 * CualquieraOtroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CualquieraOtroRepository extends \Doctrine\ORM\EntityRepository
{
}
