<?php

namespace AppBundle\Repository;

/**
 * CuerpoTramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuerpoTramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
