<?php

namespace AppBundle\Repository;

/**
 * DependenciaCiudadanoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DependenciaCiudadanoRepository extends \Doctrine\ORM\EntityRepository
{
}
