<?php

namespace AppBundle\Repository;

/**
 * Documeto_TramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Documeto_TramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
