<?php

namespace AppBundle\Repository;

/**
 * Documento_TramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Documento_TramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
