<?php

namespace AppBundle\Repository;

/**
 * DocumentoTramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentoTramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
