<?php

namespace AppBundle\Repository;

/**
 * EmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends \Doctrine\ORM\EntityRepository
{

    //Obtiene la empresa segun el NIT o Nombre
    public function findByNitOrNombre($parametro){
        $em = $this->getEntityManager();
        $sql = " SELECT e
        FROM AppBundle:Empresa e
        WHERE (e.nit = :parametro)
        OR (e.nombre = :parametro)";
        $consulta = $em->createQuery($sql);
        $consulta->setParameters(array('parametro' => $parametro));
        return $consulta->getResult();
    }

}
