<?php

namespace AppBundle\Repository;

/**
 * EmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends \Doctrine\ORM\EntityRepository
{

    //Obtiene la empresa segun el NIT o Nombre
    public function findByNitOrNombre($parametro){
        $condicion = null;
        $em = $this->getEntityManager();
        $sql = " SELECT e
        FROM AppBundle:Empresa e
        WHERE (e.nombre = :nombre)"; 
        
        if($parametro->parametro2){
            $condicion .= "AND e.nit = '" .$parametro->parametro2."'";
        }
        if($condicion){
            $sql .= $condicion;
        }
        $consulta = $em->createQuery($sql);
        $consulta->setParameters(array('nombre' => $parametro->parametro));
        return $consulta->getResult();
    }

}
