<?php

namespace AppBundle\Repository;

/**
 * FacturaInsumoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturaInsumoRepository extends \Doctrine\ORM\EntityRepository
{
}
