<?php

namespace AppBundle\Repository;

/**
 * FestivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FestivoRepository extends \Doctrine\ORM\EntityRepository
{
}
