<?php

namespace AppBundle\Repository;

/**
 * Historia_TramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Historia_TramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
