<?php

namespace AppBundle\Repository;

/**
 * HistoriaTramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriaTramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
