<?php

namespace AppBundle\Repository;

/**
 * InfraccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfraccionRepository extends \Doctrine\ORM\EntityRepository
{
}
