<?php

namespace AppBundle\Repository;

/**
 * InsumoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InsumoRepository extends \Doctrine\ORM\EntityRepository
{
}
