<?php

namespace AppBundle\Repository;

/**
 * LimitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LimitacionRepository extends \Doctrine\ORM\EntityRepository
{
}
