<?php

namespace AppBundle\Repository;

/**
 * LoteInsumoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoteInsumoRepository extends \Doctrine\ORM\EntityRepository
{

    public function getMax()
    { 
        $em = $this->getEntityManager();

        $dql = "SELECT MAX(l.rangoFin) AS maximo
            FROM AppBundle:LoteInsumo l";
        $consulta = $em->createQuery($dql);
        return $consulta->getOneOrNullResult();
    }

}
