<?php

namespace AppBundle\Repository;

/**
 * LoteInsumoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoteInsumoRepository extends \Doctrine\ORM\EntityRepository
{
}
