<?php

namespace AppBundle\Repository;

/**
 * MedidaCautelarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedidaCautelarRepository extends \Doctrine\ORM\EntityRepository
{
}
