<?php

namespace AppBundle\Repository;

/**
 * MflFacturaInfraccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MflFacturaInfraccionRepository extends \Doctrine\ORM\EntityRepository
{
}
