<?php

namespace AppBundle\Repository;

/**
 * MflInfraccionCategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MflInfraccionCategoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
