<?php

namespace AppBundle\Repository;

/**
 * MflRetefuenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MflRetefuenteRepository extends \Doctrine\ORM\EntityRepository
{
}
