<?php

namespace AppBundle\Repository;

/**
 * MgdDocumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MgdDocumentoRepository extends \Doctrine\ORM\EntityRepository
{
    //Obtiene el numero maximo de las solicitudes
    public function findMaximo($anio)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT MAX(d.consecutivo) AS maximo
            FROM AppBundle:Mgddocumento d
            WHERE YEAR(d.fechaRegistro) = :ANIO";
        $consulta = $em->createQuery($dql);
        $consulta->setParameter('ANIO', $anio);
        return $consulta->getOneOrNullResult();
    }

	//Obtiene la lista de documentos por peticionario
    public function getByPeticionario($tipoPeticionario, $identificacion = null, $entidadNombre = null, $numeroOficio = null){   
        $em = $this->getEntityManager();

        if ($tipoPeticionario == "Persona") {
        	$dql = "SELECT d
            FROM AppBundle:MgdDocumento d, AppBundle:MgdPeticionario p
            WHERE d.peticionario = p.id
            AND p.identificacion = :identificacion";

	        $consulta = $em->createQuery($dql);
	        $consulta->setParameters(array(
	            'identificacion' => $identificacion,
	        ));
        }else{
        	$dql = "SELECT d
            FROM AppBundle:MgdDocumento d, AppBundle:MgdPeticionario p
            WHERE d.peticionario = p.id
            AND p.entidadNombre = :entidadNombre
            AND d.numeroOficio = :numeroOficio";

	        $consulta = $em->createQuery($dql);
	        $consulta->setParameters(array(
	            'entidadNombre' => $entidadNombre,
	            'numeroOficio' => $numeroOficio,
	        ));
        }

        return $consulta->getResult();
    }
}
