<?php

namespace AppBundle\Repository;

/**
 * MgdMedidaCautelarVehiculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MgdMedidaCautelarVehiculoRepository extends \Doctrine\ORM\EntityRepository
{
}
