<?php

namespace AppBundle\Repository;

/**
 * MgdMedidaCautelarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MgdMedidaCautelarRepository extends \Doctrine\ORM\EntityRepository
{
}
