<?php

namespace AppBundle\Repository;

/**
 * MgdRemitenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MgdRemitenteRepository extends \Doctrine\ORM\EntityRepository
{
}
