<?php

namespace AppBundle\Repository;

/**
 * MgdTipoCorrespondenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MgdTipoCorrespondenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
