<?php

namespace AppBundle\Repository;

/**
 * ModalidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModalidadRepository extends \Doctrine\ORM\EntityRepository
{
}
