<?php

namespace AppBundle\Repository;

/**
 * ModuloSistemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuloSistemaRepository extends \Doctrine\ORM\EntityRepository
{
}
