<?php

namespace AppBundle\Repository;

/**
 * MparqGruaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MparqGruaRepository extends \Doctrine\ORM\EntityRepository
{
}
