<?php

namespace AppBundle\Repository;

/**
 * MparqGruaCiudadanoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MparqGruaCiudadanoRepository extends \Doctrine\ORM\EntityRepository
{
}
