<?php

namespace AppBundle\Repository;

/**
 * MparqPatioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MparqPatioRepository extends \Doctrine\ORM\EntityRepository
{
}
