<?php

namespace AppBundle\Repository;

/**
 * MparqEntradaSalidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MparqEntradaSalidaRepository extends \Doctrine\ORM\EntityRepository
{
}
