<?php

namespace AppBundle\Repository;

/**
 * MpersonalTalonarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MpersonalTalonarioRepository extends \Doctrine\ORM\EntityRepository
{
}
