<?php

namespace AppBundle\Repository;

/**
 * MpersonalTipoContratoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MpersonalTipoContratoRepository extends \Doctrine\ORM\EntityRepository
{
}
