<?php

namespace AppBundle\Repository;

/**
 * MpersonalAsignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MpersonalAsignacionRepository extends \Doctrine\ORM\EntityRepository
{
}
