<?php

namespace AppBundle\Repository;

/**
 * MsvCalificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsvCalificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
