<?php

namespace AppBundle\Repository;

/**
 * MsvInventarioSenialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsvInventarioSenialRepository extends \Doctrine\ORM\EntityRepository
{
    //Get the inventory of signals inventory
    public function getSearch($params){
        $em = $this->getEntityManager();

        $sql = array();"";
        if (isset($params->destinoId)) {
            $sql['destinoId'] =  "Hu09.tipoDestino = :tipoDestino";
        }

        if (isset($params->tipoDestinoId)) {
            $sql['tipoDestinoId'] = "Hu09.xDestino = :tipoDestinoSelected";
        }

        if (isset($params->tipoSenalId)) {
            $sql['tipoSenalId'] = " Hu09.tipoSenal = :tipoSenalSelected";
        }

        $where = $result = "";
        if(count($sql) > 0){
            $where = " WHERE ";
        }
        $build = "";
        foreach($sql as $key=>$value)
        {
            $build.=$value." AND ";
        }

        $result = trim($build, " AND ");

        $dql = "SELECT DISTINCT i
                FROM AppBundle:MsvSenial Hu09
                 JOIN AppBundle:MsvInventarioSenial Hu08 WITH Hu09.inventarioSenialId = Hu08.id
                 JOIN AppBundle:CfgInventario i WITH Hu08.inventario = i.id
                 JOIN AppBundle:CfgTipoSenial s WITH Hu09.tipoSenal = s.id
                 JOIN AppBundle:CfgTipoDestino d WITH Hu09.tipoDestino = d.id".$where.$result;

        $consulta = $em->createQuery($dql);

        $parameters = array();
        if (isset($params->destinoId)) {
            $parameters['tipoDestino'] = $params->destinoId;
        }

        if (isset($params->tipoDestinoId)) {
            $parameters['tipoDestinoSelected'] = $params->tipoDestinoId;
        }

        if (isset($params->tipoSenalId)) {
            $parameters['tipoSenalSelected'] = $params->tipoSenalId;
        }

        $consulta->setParameters($parameters);

        return $consulta->getResult();
    }

    //Get the inventory of signals inventory
    public function getFull(){
        $em = $this->getEntityManager();

        $dql = "SELECT Hu08
                FROM AppBundle:MsvInventarioSenial Hu08
                JOIN AppBundle:CfgInventario i WITH Hu08.inventario = i.id
                JOIN AppBundle:CfgTipoColor c WITH Hu08.tipoColor = c.id
                JOIN AppBundle:CfgTipoEstado e WITH Hu08.tipoEstado = e.id";

        $consulta = $em->createQuery($dql);

        return $consulta->getResult();
    }

}
