<?php

namespace AppBundle\Repository;

/**
 * MsvParametroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsvParametroRepository extends \Doctrine\ORM\EntityRepository
{
    
}
