<?php

namespace AppBundle\Repository;

/**
 * MsvResultadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsvResultadoRepository extends \Doctrine\ORM\EntityRepository
{
}
