<?php

namespace AppBundle\Repository;

/**
 * MsvSenialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsvSenialRepository extends \Doctrine\ORM\EntityRepository
{
    //Get the inventory of signals inventory
    public function getSearch($params){
        $em = $this->getEntityManager();

        $sql = array();"";
        if (isset($params->destinoId)) {
            $sql['destinoId'] =  "Hu09.tipoDestino = :tipoDestino";
        }

        if (isset($params->tipoDestinoId)) {
            $sql['tipoDestinoId'] = "Hu09.xDestino = :tipoDestinoSelected";
        }

        if (isset($params->tipoSenalId)) {
            $sql['tipoSenalId'] = " Hu09.tipoSenial = :tipoSenalSelected";
        }

        $where = $result = "";
        if(count($sql) > 0){
            $where = " WHERE ";
        }
        $build = "";
        foreach($sql as $key=>$value)
        {
        $build.=$value." AND ";
        }

        $result = trim($build, " AND ");

        $dql = "SELECT DISTINCT i
                FROM AppBundle:MsvSenial Hu09
                 JOIN AppBundle:MsvInventarioSenial Hu08 WITH Hu09.inventarioSenialId = Hu08.id
                 JOIN AppBundle:CfgInventario i WITH Hu08.inventario = i.id
                 JOIN AppBundle:CfgTipoSenial s WITH Hu09.tipoSenial = s.id
                 JOIN AppBundle:CfgTipoDestino d WITH Hu09.tipoDestino = d.id".$where.$result;

        $consulta = $em->createQuery($dql);

        $parameters = array();
        if (isset($params->destinoId)) {
            $parameters['tipoDestino'] = $params->destinoId;
        }

        if (isset($params->tipoDestinoId)) {
            $parameters['tipoDestinoSelected'] = $params->tipoDestinoId;
        }

        if (isset($params->tipoSenalId)) {
            $parameters['tipoSenalSelected'] = $params->tipoSenalId;
        }

        $consulta->setParameters($parameters);

        return $consulta->getResult();
    }

    //Get the inventory of signals inventory
    public function getBySenial($params){
        $em = $this->getEntityManager();

        $dql = "SELECT Hu08.id AS ID,
                i.numero AS NUMERO_INVENTARIO,
                i.fecha AS FECHA_INVENTARIO,
                Hu08.fecha AS FECHA_INGRESO,
                Hu08.unidad AS UNIDAD,
                c.nombre AS COLOR,
                c.hex AS HEX,
                Hu08.latitud AS LATITUD,
                Hu08.longitud AS LONGITUD,
                Hu08.direccion AS DIRECCION,
                Hu08.codigo AS CODIGO,
                Hu08.logo AS LOGO,
                Hu08.nombre AS NOMBRE,
                Hu08.valor AS VALOR,
                e.nombre AS ESTADO,
                Hu08.cantidad AS CANTIDAD,
                Hu09.archivo AS ARCHIVO
                FROM AppBundle:MsvInventarioSenial Hu08
                JOIN AppBundle:MsvSenial Hu09 WITH Hu09.inventarioSenialId = Hu08.id
                JOIN AppBundle:CfgInventario i WITH Hu08.inventario = i.id
                JOIN AppBundle:CfgTipoColor c WITH Hu08.tipoColor = c.id
                JOIN AppBundle:CfgTipoEstado e WITH Hu08.tipoEstado = e.id
                WHERE ((i.id = :idInv)
                AND (i.fecha = :dateInv)
                AND (Hu09.tipoSenial = :typeSen))";

        $consulta = $em->createQuery($dql);
        $consulta->setParameters(array(
            'idInv' => @$params->idInv,
            'dateInv' => @$params->dateInv,
            'typeSen' => @$params->typeSen
        ));

        return $consulta->getResult();
    }

    //Get the inventory of signals inventory
    public function getFull(){
        $em = $this->getEntityManager();

        $dql = "SELECT Hu08
                FROM AppBundle:MsvInventarioSenial Hu08
                JOIN AppBundle:MsvSenial Hu09 WITH Hu09.inventarioSenialId = Hu08.id
                JOIN AppBundle:CfgInventario i WITH Hu08.inventario = i.id
                JOIN AppBundle:CfgTipoColor c WITH Hu08.tipoColor = c.id
                JOIN AppBundle:CfgTipoEstado e WITH Hu08.tipoEstado = e.id";

        $consulta = $em->createQuery($dql);

        return $consulta->getResult();
    }

    //Get the inventory of signals inventory
    public function getFullInv(){
        $em = $this->getEntityManager();

        $dql = "SELECT Hu08.id AS ID,
                i.numero AS NUMERO_INVENTARIO,
                i.fecha AS FECHA_INVENTARIO,
                d.nombre AS TIPO_DESTINO,
                (CASE
                 WHEN (d.id = 1)
                 THEN b.nombre
                 ELSE m.nombre
                 END) AS NOMBRE_DESTINO,
                s.nombre AS TIPO,
                Hu08.fecha AS FECHA_INGRESO,
                Hu08.unidad AS UNIDAD,
                c.nombre AS COLOR,
                c.hex AS HEX,
                Hu08.latitud AS LATITUD,
                Hu08.longitud AS LONGITUD,
                Hu08.codigo AS CODIGO,
                Hu08.logo AS LOGO,
                Hu08.nombre AS NOMBRE,
                Hu08.valor AS VALOR,
                e.nombre AS ESTADO,
                Hu08.cantidad AS CANTIDAD,
                Hu09.archivo AS ARCHIVO
                FROM AppBundle:MsvInventarioSenial Hu08
                JOIN AppBundle:MsvSenial Hu09 WITH Hu09.inventarioSenialId = Hu08.id
                JOIN AppBundle:CfgInventario i WITH Hu08.inventario = i.id
                JOIN AppBundle:CfgTipoColor c WITH Hu08.tipoColor = c.id
                JOIN AppBundle:CfgTipoEstado e WITH Hu08.tipoEstado = e.id
                JOIN AppBundle:CfgTipoDestino d WITH Hu09.tipoDestino = d.id
                JOIN AppBundle:CfgTipoSenial s WITH Hu09.tipoSenial = s.id
                LEFT JOIN AppBundle:CfgBodega b WITH Hu09.xDestino = (CASE
                                    WHEN (d.id = 1)
                                    THEN b.id
                                    ELSE ''
                                    END)
                LEFT JOIN AppBundle:Municipio m WITH Hu09.xDestino = (CASE
                                    WHEN (d.id = 2)
                                    THEN m.id
                                    ELSE ''
                                    END)";

        $consulta = $em->createQuery($dql);

        return $consulta->getResult();
    }

    //Get the inventory of signals inventory
    public function getByInv($data){

        $param = array();
        $get = explode("_", $data);
        $param['idInv'] = $get[0];
        $param['dateInv'] = $get[1];
        $param['typeSen'] = $get[2];

        $em = $this->getEntityManager();

        $dql = "SELECT Hu08.id AS ID,
                i.numero AS NUMERO_INVENTARIO,
                i.fecha AS FECHA_INVENTARIO,
                d.nombre AS TIPO_DESTINO,
                (CASE
                 WHEN (d.id = 1)
                 THEN b.nombre
                 ELSE m.nombre
                 END) AS NOMBRE_DESTINO,
                s.nombre AS TIPO,
                Hu08.fecha AS FECHA_INGRESO,
                Hu08.unidad AS UNIDAD,
                c.nombre AS COLOR,
                c.hex AS HEX,
                Hu08.latitud AS LATITUD,
                Hu08.longitud AS LONGITUD,
                Hu08.codigo AS CODIGO,
                Hu08.logo AS LOGO,
                Hu08.nombre AS NOMBRE,
                Hu08.valor AS VALOR,
                e.nombre AS ESTADO,
                Hu08.cantidad AS CANTIDAD,
                Hu09.archivo AS ARCHIVO
                FROM AppBundle:MsvInventarioSenial Hu08
                JOIN AppBundle:MsvSenial Hu09 WITH Hu09.inventarioSenialId = Hu08.id
                JOIN AppBundle:CfgInventario i WITH Hu08.inventario = i.id
                JOIN AppBundle:CfgTipoColor c WITH Hu08.tipoColor = c.id
                JOIN AppBundle:CfgTipoEstado e WITH Hu08.tipoEstado = e.id
                JOIN AppBundle:CfgTipoDestino d WITH Hu09.tipoDestino = d.id
                JOIN AppBundle:CfgTipoSenial s WITH Hu09.tipoSenial = s.id
                LEFT JOIN AppBundle:CfgBodega b WITH Hu09.xDestino = (CASE
                                    WHEN (d.id = 1)
                                    THEN b.id
                                    ELSE ''
                                    END)
                LEFT JOIN AppBundle:Municipio m WITH Hu09.xDestino = (CASE
                                    WHEN (d.id = 2)
                                    THEN m.id
                                    ELSE ''
                                    END)
                WHERE ((i.id = :idInv)
                AND (i.fecha = :dateInv)
                AND (Hu09.tipoSenial = :typeSen))";

        $consulta = $em->createQuery($dql);
        $consulta->setParameters(array(
            'idInv' => $param['idInv'],
            'dateInv' => $param['dateInv'],
            'typeSen' => $param['typeSen']
        ));

        return $consulta->getResult();
    }
}
