<?php

namespace AppBundle\Repository;

/**
 * MsvTConsecutivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsvTConsecutivoRepository extends \Doctrine\ORM\EntityRepository
{
}
