<?php

namespace AppBundle\Repository;

/**
 * MsvTalonarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsvTalonarioRepository extends \Doctrine\ORM\EntityRepository
{
}
