<?php

namespace AppBundle\Repository;

/**
 * MsvVariableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsvVariableRepository extends \Doctrine\ORM\EntityRepository
{
}
