<?php

namespace AppBundle\Repository;

/**
 * OrganismoTransitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganismoTransitoRepository extends \Doctrine\ORM\EntityRepository
{
         public function getBySede($identificacionUsuario)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT ot
            FROM UsuarioBundle:Usuario u, AppBundle:MpersonalFuncionario mpf, AppBundle:OrganismoTransito ot
            WHERE u.identificacion = :identificacionUsuario
            AND u.ciudadano = mpf.ciudadano
            AND mpf.sedeOperativa = ot.sedeOperativa";
        $consulta = $em->createQuery($dql);

        $consulta->setParameters(array(
            'identificacionUsuario' => $identificacionUsuario,
        ));

        return $consulta->getOneOrNullResult();
    }
}
