<?php

namespace AppBundle\Repository;

/**
 * PagoTramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagoTramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
