<?php

namespace AppBundle\Repository;

/**
 * Pago_TramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Pago_TramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
