<?php

namespace AppBundle\Repository;

/**
 * PeticionarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeticionarioRepository extends \Doctrine\ORM\EntityRepository
{
}
