<?php

namespace AppBundle\Repository;

/**
 * Propietario_VehiculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Propietario_VehiculoRepository extends \Doctrine\ORM\EntityRepository
{
}
