<?php

namespace AppBundle\Repository;

/**
 * RadioAccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RadioAccionRepository extends \Doctrine\ORM\EntityRepository
{
}
