<?php

namespace AppBundle\Repository;

/**
 * RegistroDocumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroDocumentoRepository extends \Doctrine\ORM\EntityRepository
{
}
