<?php

namespace AppBundle\Repository;

/**
 * SedeOperativaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SedeOperativaRepository extends \Doctrine\ORM\EntityRepository
{
}
