<?php

namespace AppBundle\Repository;

/**
 * Tipos_IdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tipos_IdRepository extends \Doctrine\ORM\EntityRepository
{
}
