<?php

namespace AppBundle\Repository;

/**
 * TipoCorrespondenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoCorrespondenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
