<?php

namespace AppBundle\Repository;

/**
 * TipoTramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoTramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
