<?php

namespace AppBundle\Repository;

/**
 * TramiteSolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TramiteSolicitudRepository extends \Doctrine\ORM\EntityRepository
{
    // public function getTramitesVehiculo($vehiculoId)
    // {   
    //     $em = $this->getEntityManager();
    //     $dql = "SELECT ts
    //         FROM AppBundle:TramiteSolicitud ts, AppBundle:TramiteFactura tf, AppBundle:Factura f
    //         WHERE ((ts.tramiteFactura = tf.id)
    //         AND (tf.factura = f.id)
    //         AND (f.vehiculo = :vehiculoId)
    //         )
    //         ";
    //     $consulta = $em->createQuery($dql);
        
    //     $consulta->setParameters(array(
    //         'vehiculoId' => $vehiculoId,
    //     ));
    //     return $consulta->getResult();
    // }
    public function getTramiteReportes()
    {   
        
        
        $em = $this->getEntityManager();
        $dql = "SELECT ts, count(ts.tramiteFactura) as conteo
                FROM AppBundle:tramiteSolicitud ts
               
                GROUP BY ts.tramiteFactura
                ORDER BY ts.id ASC
            
            ";
        $consulta = $em->createQuery($dql);
        
      
       
        return $consulta->getResult();
    }

//      SELECT COUNT(tramite_factura_id) AS conteo, tramite_factura_id
//      FROM `tramite_solicitud`
//      GROUP BY tramite_factura_id
//      ORDER BY tramite_factura_id ASC



    
}
