<?php

namespace AppBundle\Repository;

/**
 * TramiteSistemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TramiteSistemaRepository extends \Doctrine\ORM\EntityRepository
{
}
