<?php

namespace AppBundle\Repository;

/**
 * TramitePrecioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TramitePrecioRepository extends \Doctrine\ORM\EntityRepository
{
}
