<?php

namespace AppBundle\Repository;

/**
 * TramiteEspecificoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TramiteEspecificoRepository extends \Doctrine\ORM\EntityRepository
{
}
