<?php

namespace AppBundle\Repository;

/**
 * TramiteSolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TramiteSolicitudRepository extends \Doctrine\ORM\EntityRepository
{
    // public function getTramitesVehiculo($vehiculoId)
    // {   
    //     $em = $this->getEntityManager();
    //     $dql = "SELECT ts
    //         FROM AppBundle:TramiteSolicitud ts, AppBundle:TramiteFactura tf, AppBundle:Factura f
    //         WHERE ((ts.tramiteFactura = tf.id)
    //         AND (tf.factura = f.id)
    //         AND (f.vehiculo = :vehiculoId)
    //         )
    //         ";
    //     $consulta = $em->createQuery($dql);
        
    //     $consulta->setParameters(array(
    //         'vehiculoId' => $vehiculoId,
    //     ));
    //     return $consulta->getResult();
    // }
}
