<?php

namespace AppBundle\Repository;

/**
 * TramiteFacturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TramiteFacturaRepository extends \Doctrine\ORM\EntityRepository
{
    // public function getFacturaModulo($moduloId, $facturaId, $vehiculoId)
    // {
    //     $em = $this->getEntityManager();
    //     $dql = "SELECT tf
    //         FROM AppBundle:TramiteFactura tf, AppBundle:Factura f, AppBundle:Modulo m, AppBundle:TramitePrecio tp
    //         WHERE tf.factura = f.id
    //         AND f.id = :facturaId";
    //     $consulta = $em->createQuery($dql);

    //     $consulta->setParameters(array(
    //         'facturaId' => $facturaId,
    //     ));
    //     return $consulta->getResult();

    // }
    public function getFacturaModulo($moduloId, $facturaId, $vehiculoId)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT tf
            FROM AppBundle:TramiteFactura tf, AppBundle:Factura f, AppBundle:Modulo m, AppBundle:TramitePrecio tp
            WHERE tf.factura = f.id
            AND f.numero = :facturaId"; 
        $consulta = $em->createQuery($dql);

        $consulta->setParameters(array(
            'facturaId' => $facturaId,
        ));
        return $consulta->getResult();

    }

    public function getByFacturaAndTramite($facturaId, $tramiteId)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT tf
            FROM AppBundle:TramiteFactura tf, AppBundle:Factura f, AppBundle:Tramite t, AppBundle:TramitePrecio tp
            WHERE tf.factura = f.id
            AND tf.tramitePrecio = tp.id
            AND tp.tramite = t.id
            AND t.id = :tramiteId
            AND f.id = :facturaId"; 
        $consulta = $em->createQuery($dql);

        $consulta->setParameters(array(
            'facturaId' => $facturaId,
            'tramiteId' => $tramiteId,
        ));
        return $consulta->getOneOrNullResult();

    }
}
