<?php

namespace AppBundle\Repository;

/**
 * VarianteTramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VarianteTramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
