<?php

namespace AppBundle\Repository;

/**
 * VarianteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VarianteRepository extends \Doctrine\ORM\EntityRepository
{
}
