<?php

namespace AppBundle\Repository;

/**
 * VehiculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculoRepository extends \Doctrine\ORM\EntityRepository
{
    //Obtiene la lista de Usuario disponibles para vincular en la Campaña
    public function getVehiculoCampo($campo)
    {   
        $em = $this->getEntityManager();
        $dql = "SELECT v
            FROM AppBundle:Vehiculo v, AppBundle:CfgPlaca p
            WHERE ((v.placa = p.id)
            AND (p.numero = :campo))
            OR (v.vin = :campo)
            OR (v.chasis = :campo)
            OR (v.serie = :campo)
            OR (v.motor = :campo)
            ";
        $consulta = $em->createQuery($dql);
        
        $consulta->setParameters(array(
            'campo' => $campo,
        ));
        return $consulta->getOneOrNullResult();
    }

    public function getRna()
    {   
        $em = $this->getEntityManager();
        $dql = "SELECT v
            FROM AppBundle:Vehiculo v, AppBundle:Clase c, AppBundle:Modulo m
            WHERE c.id = v.clase
            AND m.id = c.modulo
            AND m.id = 1
            AND v.estado = true";
        $consulta = $em->createQuery($dql);
        return $consulta->getResult();
    }

    //Obtiene el vehículo según un parametro
    public function findOneByParametro($parametro)
    {   
        $em = $this->getEntityManager();
        $dql = "SELECT v
            FROM AppBundle:Vehiculo v, AppBundle:CfgPlaca p, AppBundle:PropietarioVehiculo pv, AppBundle:Ciudadano c, UsuarioBundle:Usuario u
            WHERE ((v.placa = p.id)
            AND (p.numero = :parametro))
            OR((v.id = pv.vehiculo)
            AND (pv.ciudadano = c.id)
            AND(c.usuario = u.id)
            AND(u.identificacion = :parametro))
            OR (v.vin = :parametro)
            OR (v.chasis = :parametro)
            OR (v.serie = :parametro)
            OR (v.motor = :parametro)";
        $consulta = $em->createQuery($dql);
        
        $consulta->setParameters(array(
            'parametro' => $parametro,
        ));
        return $consulta->getOneOrNullResult();
    }
}
