<?php

namespace AppBundle\Repository;

/**
 * VehiculoTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculoTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
