<?php

namespace AppBundle\Repository;

/**
 * VehiculoMaquinariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculoMaquinariaRepository extends \Doctrine\ORM\EntityRepository
{
}
