<?php

namespace AppBundle\Repository;

/**
 * VehiculoAcreedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculoAcreedorRepository extends \Doctrine\ORM\EntityRepository
{
}
