<?php

namespace AppBundle\Repository;

/**
 * VehiculoLimitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculoLimitacionRepository extends \Doctrine\ORM\EntityRepository
{
}
