<?php

namespace AppBundle\Repository;

/**
 * VehiculoRemolqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculoRemolqueRepository extends \Doctrine\ORM\EntityRepository
{
}
