<?php

namespace AppBundle\Repository;

/**
 * VehiculoRemolqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculoRemolqueRepository extends \Doctrine\ORM\EntityRepository
{
    public function getVehiculoCampo()
    {   
        $em = $this->getEntityManager();
        $dql = "SELECT vr
            FROM AppBundle:Vehiculo v, AppBundle:VehiculoRemolque vr
            WHERE ((v.id = vr.vehiculo)
            AND (v.estado = :estado))";
        $consulta = $em->createQuery($dql);
        
        $consulta->setParameters(array(
            'estado' => 1,
        ));
        return $consulta->getResult();
    }
}
