<?php

namespace AppBundle\Repository;

/**
 * VehiculoPesadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculoPesadoRepository extends \Doctrine\ORM\EntityRepository
{
}
