<?php

namespace AppBundle\Repository;

/**
 * VehiculoMaquinariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculoMaquinariaRepository extends \Doctrine\ORM\EntityRepository
{
    // 
    public function getVehiculoCampo()
    {   
          
        $em = $this->getEntityManager();
        $dql = "SELECT vm
            FROM AppBundle:Vehiculo v, AppBundle:VehiculoMaquinaria vm
            WHERE ((v.id = vm.vehiculo)
            AND (v.estado = :estado))
            ";
        $consulta = $em->createQuery($dql);
        
        $consulta->setParameters(array(
            'estado' => 1,
        ));
        return $consulta->getResult();
    }
}
