jhweb_vehiculo:
    resource: "@JHWEBVehiculoBundle/Controller/"
    type:     annotation
    prefix:   /vehiculo
    
app_cfg_asignacion_placa_sede:
    resource: "@AppBundle/Controller/CfgAsignacionPlacaSedeController.php"
    type:     annotation

app_cfg_tipo_clase:
    resource: "@AppBundle/Controller/CfgTipoClaseController.php"
    type:     annotation

app_cfg_tipo_vehiculo:
    resource: "@AppBundle/Controller/CfgTipoVehiculoController.php"
    type:     annotation

app_cfg_cargo:
    resource: "@AppBundle/Controller/CfgCargoController.php"
    type:     annotation

app_msv_inventario_senial:
    resource: "@AppBundle/Controller/MsvInventarioSenialController.php"
    type:     annotation

app_cfg_comparendo_estado:
    resource: "@AppBundle/Controller/CfgComparendoEstadoController.php"
    type:     annotation
    
app_cfg_objeto_fijo:
    resource: "@AppBundle/Controller/CfgObjetoFijoController.php"
    type:     annotation
    
app_msv_senial:
    resource: "@AppBundle/Controller/MsvSenialController.php"
    type:     annotation
    
app_cfg_tipo_senial:
    resource: "@AppBundle/Controller/CfgTipoSenialController.php"
    type:     annotation

app_cfg_bodega:
    resource: "@AppBundle/Controller/CfgBodegaController.php"
    type:     annotation

app_cfg_valor_vehiculo:
    resource: "@AppBundle/Controller/CfgValorVehiculoController.php"
    type:     annotation

app_vehiculo_remolque:
    resource: "@AppBundle/Controller/VehiculoRemolqueController.php"
    type:     annotation

app_licencia_conduccion:
    resource: "@AppBundle/Controller/LicenciaConduccionController.php"
    type:     annotation
    
app_vehiculo_limitacion:
    resource: "@AppBundle/Controller/VehiculoLimitacionController.php"
    type:     annotation

app_limitacion_datos:
    resource: "@AppBundle/Controller/LimitacionDatosController.php"
    type:     annotation

app_cfg_entidad_judicial:
    resource: "@AppBundle/Controller/CfgEntidadJudicialController.php"
    type:     annotation

app_cfg_tipo_proceso:
    resource: "@AppBundle/Controller/CfgTipoProcesoController.php"
    type:     annotation

app_limitacion:
    resource: "@AppBundle/Controller/CfgLimitacionController.php"
    type:     annotation

app_cfg_licencia_conduccion_categoria:
    resource: "@AppBundle/Controller/CfgLicenciaConduccionCategoriaController.php"
    type:     annotation

app_cfg_origen_registro:
    resource: "@AppBundle/Controller/CfgOrigenRegistroController.php"
    type:     annotation

app_insumo:
    resource: "@AppBundle/Controller/InsumoController.php"
    type:     annotation

app_lote_insumo:
    resource: "@AppBundle/Controller/LoteInsumoController.php"
    type:     annotation

app_caso_insumo:
    resource: "@AppBundle/Controller/CasoInsumoController.php"
    type:     annotation
    
app_vehiculo_maquinaria:
    resource: "@AppBundle/Controller/VehiculoMaquinariaController.php"
    type:     annotation

app_tramite_traslado:
    resource: "@AppBundle/Controller/TramiteTrasladoController.php"
    type:     annotation

app_vehiculo_acreedor:
    resource: "@AppBundle/Controller/VehiculoAcreedorController.php"
    type:     annotation

app_cfg_modalidad_transporte:
    resource: "@AppBundle/Controller/CfgModalidadTransporteController.php"
    type:     annotation

app_cfg_radio_accion:
    resource: "@AppBundle/Controller/CfgRadioAccionController.php"
    type:     annotation

app_cfg_tipo_alerta:
    resource: "@AppBundle/Controller/CfgTipoAlertaController.php"
    type:     annotation
    
app_msv_calificacion:
    resource: "@AppBundle/Controller/MsvCalificacionController.php"
    type:     annotation

app_msv_criterio:
    resource: "@AppBundle/Controller/MsvCriterioController.php"
    type:     annotation

app_msv_variable:
    resource: "@AppBundle/Controller/MsvVariableController.php"
    type:     annotation

app_msv_parametro:
    resource: "@AppBundle/Controller/MsvParametroController.php"
    type:     annotation

app_msv_categoria:
    resource: "@AppBundle/Controller/MsvCategoriaController.php"
    type:     annotation

app_msv_tc_asignacion:
    resource: "@AppBundle/Controller/MsvTCAsignacionController.php"
    type:     annotation

app_mpersonal_asignacion:
    resource: "@AppBundle/Controller/MpersonalAsignacionController.php"
    type:     annotation

app_mpersonal_horario:
    resource: "@AppBundle/Controller/MpersonalHorarioController.php"
    type:     annotation

app_mparq_entrada_salida:
    resource: "@AppBundle/Controller/MparqEntradaSalidaController.php"
    type:     annotation

app_mparq_grua_ciudadano:
    resource: "@AppBundle/Controller/MparqGruaCiudadanoController.php"
    type:     annotation

app_mparq_grua:
    resource: "@AppBundle/Controller/MparqGruaController.php"
    type:     annotation

app_mpersonal_comparendo:
    resource: "@AppBundle/Controller/MpersonalComparendoController.php"
    type:     annotation

app_mpersonal_talonario:
    resource: "@AppBundle/Controller/MpersonalTalonarioController.php"
    type:     annotation

app_msv_caracterizacion:
    resource: "@AppBundle/Controller/MsvCaracterizacionController.php"
    type:     annotation

app_cfg_smlmv:
    resource: "@AppBundle/Controller/CfgSmlmvController.php"
    type:     annotation

app_mfl_infraccion:
    resource: "@AppBundle/Controller/MflInfraccionController.php"
    type:     annotation

app_mfl_infraccion_categoria:
    resource: "@AppBundle/Controller/MflInfraccionCategoriaController.php"
    type:     annotation

app_cfg_auditoria:
    resource: "@AppBundle/Controller/CfgAuditoriaController.php"
    type:     annotation

app_mpersonal_funcionario:
    resource: "@AppBundle/Controller/MpersonalFuncionarioController.php"
    type:     annotation

app_mpersonal_tipo_contrato:
    resource: "@AppBundle/Controller/MpersonalTipoContratoController.php"
    type:     annotation

app_mpersonal_tipo_contrato:
    resource: "@AppBundle/Controller/MpersonalTipoContratoController.php"
    type:     annotation
    
app_mparq_costo_trayecto:
    resource: "@AppBundle/Controller/MparqCostoTrayectoController.php"
    type:     annotation

app_cfg_festivo:
    resource: "@AppBundle/Controller/CfgFestivoController.php"
    type:     annotation

app_mgd_documento:
    resource: "@AppBundle/Controller/MgdDocumentoController.php"
    type:     annotation

app_mgd_medida_cautelar:
    resource: "@AppBundle/Controller/MgdMedidaCautelarController.php"
    type:     annotation

app_mgd_peticionario:
    resource: "@AppBundle/Controller/MgdPeticionarioController.php"
    type:     annotation

app_mgd_tipo_correspondencia:
    resource: "@AppBundle/Controller/MgdTipoCorrespondenciaController.php"
    type:     annotation

app_empresa:
    resource: "@AppBundle/Controller/EmpresaController.php"
    type:     annotation

app_representante_empresa:
    resource: "@AppBundle/Controller/RepresentanteEmpresaController.php"
    type:     annotation

app_concepto_parametro:
    resource: "@AppBundle/Controller/ConceptoParametroController.php"
    type:     annotation

app_concepto_parametro_tramite:
    resource: "@AppBundle/Controller/ConceptoParametroTramiteController.php"
    type:     annotation

app_parametro:
    resource: "@AppBundle/Controller/ParametroController.php"
    type:     annotation

app_factura_sustrato:
    resource: "@AppBundle/Controller/FacturaSustratoController.php"
    type:     annotation

app_condicion_ingreso:
    resource: "@AppBundle/Controller/CondicionIngresoController.php"
    type:     annotation

app_origen_registro:
    resource: "@AppBundle/Controller/OrigenRegistroController.php"
    type:     annotation

app_pais:
    resource: "@AppBundle/Controller/PaisController.php"
    type:     annotation

app_tipo_recaudo:
    resource: "@AppBundle/Controller/TipoRecaudoController.php"
    type:     annotation

app_tipo_vehiculo:
    resource: "@AppBundle/Controller/TipoVehiculoController.php"
    type:     annotation

app_tramite_precio:
    resource: "@AppBundle/Controller/TramitePrecioController.php"
    type:     annotation

app_tipo_sociedad:
    resource: "@AppBundle/Controller/TipoSociedadController.php"
    type:     annotation

app_sustrato:
    resource: "@AppBundle/Controller/SustratoController.php"
    type:     annotation

app_tramite_factura:
    resource: "@AppBundle/Controller/TramiteFacturaController.php"
    type:     annotation

app_tramite_solicitud:
    resource: "@AppBundle/Controller/TramiteSolicitudController.php"
    type:     annotation

app_factura:
    resource: "@AppBundle/Controller/FacturaController.php"
    type:     annotation

app_grupo_sanguineo:
    resource: "@AppBundle/Controller/GrupoSanguineoController.php"
    type:     annotation

app_genero:
    resource: "@AppBundle/Controller/GeneroController.php"
    type:     annotation

app_sede_operativa:
    resource: "@AppBundle/Controller/SedeOperativaController.php"
    type:     annotation

app_inmovilizacion:
    resource: "@AppBundle/Controller/InmovilizacionController.php"
    type:     annotation

app_seguimiento_entrega:
    resource: "@AppBundle/Controller/SeguimientoEntregaController.php"
    type:     annotation

app_comparendo:
    resource: "@AppBundle/Controller/ComparendoController.php"
    type:     annotation

app_dependencia:
    resource: "@AppBundle/Controller/DependenciaController.php"
    type:     annotation

app_default:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

usuario:
    resource: "@UsuarioBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


