<<<<<<< HEAD
jhweb_seguridad_vial_sv_cfg_tipo_controles_transito:
    resource: "@JHWEBSeguridadVialBundle/Controller/SvCfgTipoControlesTransitoController.php"
    type:     annotation

jhweb_seguridad_vial_sv_cfg_controles_transito:
    resource: "@JHWEBSeguridadVialBundle/Controller/SvCfgControlesTransitoController.php"
    type:     annotation
=======
jhweb_personal:
    resource: "@JHWEBPersonalBundle/Controller/"
    type:     annotation
    prefix:   /personal
>>>>>>> 0393c2c94d7d4148f60f81fd85534a4fc58f3e89

jhweb_insumo:
    resource: "@JHWEBInsumoBundle/Controller/"
    type:     annotation
    prefix:   /insumo

jhweb_gestion_documental:
    resource: "@JHWEBGestionDocumentalBundle/Controller/"
    type:     annotation
    prefix:   /gestiondocumental

jhweb_contravencional:
    resource: "@JHWEBContravencionalBundle/Controller/"
    type:     annotation
    prefix:   /contravencional

jhweb_seguridad_vial:
    resource: "@JHWEBSeguridadVialBundle/Controller/"
    type:     annotation
    prefix:   /seguridadvial

jhweb_config:
    resource: "@JHWEBConfigBundle/Controller/"
    type:     annotation
    prefix:   /configuracion

jhweb_vehiculo:
    resource: "@JHWEBVehiculoBundle/Controller/"
    type:     annotation
    prefix:   /vehiculo
    
usuario:
    resource: "@UsuarioBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


