app_cfg_placa:
    resource: "@AppBundle/Controller/CfgPlacaController.php"
    type:     annotation

app_mfl_infraccion_categoria:
    resource: "@AppBundle/Controller/MflInfraccionCategoriaController.php"
    type:     annotation

app_cfg_auditoria:
    resource: "@AppBundle/Controller/CfgAuditoriaController.php"
    type:     annotation

app_mparq_costo_trayecto:
    resource: "@AppBundle/Controller/MparqCostoTrayectoController.php"
    type:     annotation

app_cfg_festivo:
    resource: "@AppBundle/Controller/CfgFestivoController.php"
    type:     annotation

app_mgd_documento:
    resource: "@AppBundle/Controller/MgdDocumentoController.php"
    type:     annotation

app_mgd_medida_cautelar:
    resource: "@AppBundle/Controller/MgdMedidaCautelarController.php"
    type:     annotation

app_mgd_peticionario:
    resource: "@AppBundle/Controller/MgdPeticionarioController.php"
    type:     annotation

app_mgd_tipo_correspondencia:
    resource: "@AppBundle/Controller/MgdTipoCorrespondenciaController.php"
    type:     annotation

app_representante_empresa:
    resource: "@AppBundle/Controller/RepresentanteEmpresaController.php"
    type:     annotation

app_concepto_parametro:
    resource: "@AppBundle/Controller/ConceptoParametroController.php"
    type:     annotation

app_concepto_parametro_tramite:
    resource: "@AppBundle/Controller/ConceptoParametroTramiteController.php"
    type:     annotation

app_parametro:
    resource: "@AppBundle/Controller/ParametroController.php"
    type:     annotation

app_factura_sustrato:
    resource: "@AppBundle/Controller/FacturaSustratoController.php"
    type:     annotation

app_radio_accion:
    resource: "@AppBundle/Controller/RadioAccionController.php"
    type:     annotation

app_condicion_ingreso:
    resource: "@AppBundle/Controller/CondicionIngresoController.php"
    type:     annotation

app_origen_registro:
    resource: "@AppBundle/Controller/OrigenRegistroController.php"
    type:     annotation

app_pais:
    resource: "@AppBundle/Controller/PaisController.php"
    type:     annotation

app_tipo_recaudo:
    resource: "@AppBundle/Controller/TipoRecaudoController.php"
    type:     annotation

app_tipo_vehiculo:
    resource: "@AppBundle/Controller/TipoVehiculoController.php"
    type:     annotation

app_tramite_precio:
    resource: "@AppBundle/Controller/TramitePrecioController.php"
    type:     annotation

app_tipo_sociedad:
    resource: "@AppBundle/Controller/TipoSociedadController.php"
    type:     annotation

app_sustrato:
    resource: "@AppBundle/Controller/SustratoController.php"
    type:     annotation

app_tramite_factura:
    resource: "@AppBundle/Controller/TramiteFacturaController.php"
    type:     annotation

app_tramite_solicitud:
    resource: "@AppBundle/Controller/TramiteSolicitudController.php"
    type:     annotation

app_factura:
    resource: "@AppBundle/Controller/FacturaController.php"
    type:     annotation

app_grupo_sanguineo:
    resource: "@AppBundle/Controller/GrupoSanguineoController.php"
    type:     annotation

app_genero:
    resource: "@AppBundle/Controller/GeneroController.php"
    type:     annotation

app_sede_operativa:
    resource: "@AppBundle/Controller/SedeOperativaController.php"
    type:     annotation

app_infraccion:
    resource: "@AppBundle/Controller/InfraccionController.php"
    type:     annotation

app_inmovilizacion:
    resource: "@AppBundle/Controller/InmovilizacionController.php"
    type:     annotation

app_seguimiento_entrega:
    resource: "@AppBundle/Controller/SeguimientoEntregaController.php"
    type:     annotation

app_comparendo:
    resource: "@AppBundle/Controller/ComparendoController.php"
    type:     annotation

app_agente_transito:
    resource: "@AppBundle/Controller/AgenteTransitoController.php"
    type:     annotation

app_modulo_sistema:
    resource: "@AppBundle/Controller/ModuloSistemaController.php"
    type:     annotation

app_dependencia:
    resource: "@AppBundle/Controller/DependenciaController.php"
    type:     annotation

usuario:
    resource: "@UsuarioBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


