app_sede_operativa:
    resource: "@AppBundle/Controller/SedeOperativaController.php"
    type:     annotation

app_infraccion:
    resource: "@AppBundle/Controller/InfraccionController.php"
    type:     annotation

app_inmovilizacion:
    resource: "@AppBundle/Controller/InmovilizacionController.php"
    type:     annotation

app_seguimiento_entrega:
    resource: "@AppBundle/Controller/SeguimientoEntregaController.php"
    type:     annotation

app_comparendo:
    resource: "@AppBundle/Controller/ComparendoController.php"
    type:     annotation

app_agente_transito:
    resource: "@AppBundle/Controller/AgenteTransitoController.php"
    type:     annotation

app_modulo_sistema:
    resource: "@AppBundle/Controller/ModuloSistemaController.php"
    type:     annotation

app_dependencia:
    resource: "@AppBundle/Controller/DependenciaController.php"
    type:     annotation

usuario:
    resource: "@UsuarioBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


