app_tipo_recaudo:
    resource: "@AppBundle/Controller/TipoRecaudoController.php"
    type:     annotation

app_tipo_vehiculo:
    resource: "@AppBundle/Controller/TipoVehiculoController.php"
    type:     annotation

app_tramite_precio:
    resource: "@AppBundle/Controller/TramitePrecioController.php"
    type:     annotation

app_tipo_sociedad:
    resource: "@AppBundle/Controller/TipoSociedadController.php"
    type:     annotation

app_tipo_documento:
    resource: "@AppBundle/Controller/TipoDocumentoController.php"
    type:     annotation

app_registro_documento:
    resource: "@AppBundle/Controller/RegistroDocumentoController.php"
    type:     annotation

app_peticionario:
    resource: "@AppBundle/Controller/PeticionarioController.php"
    type:     annotation

app_sustrato:
    resource: "@AppBundle/Controller/SustratoController.php"
    type:     annotation

app_tramite_factura:
    resource: "@AppBundle/Controller/TramiteFacturaController.php"
    type:     annotation

app_tramite_solicitud:
    resource: "@AppBundle/Controller/TramiteSolicitudController.php"
    type:     annotation

app_factura:
    resource: "@AppBundle/Controller/FacturaController.php"
    type:     annotation

app_grupo_sanguineo:
    resource: "@AppBundle/Controller/GrupoSanguineoController.php"
    type:     annotation

app_genero:
    resource: "@AppBundle/Controller/GeneroController.php"
    type:     annotation

app_sede_operativa:
    resource: "@AppBundle/Controller/SedeOperativaController.php"
    type:     annotation

app_infraccion:
    resource: "@AppBundle/Controller/InfraccionController.php"
    type:     annotation

app_inmovilizacion:
    resource: "@AppBundle/Controller/InmovilizacionController.php"
    type:     annotation

app_seguimiento_entrega:
    resource: "@AppBundle/Controller/SeguimientoEntregaController.php"
    type:     annotation

app_comparendo:
    resource: "@AppBundle/Controller/ComparendoController.php"
    type:     annotation

app_agente_transito:
    resource: "@AppBundle/Controller/AgenteTransitoController.php"
    type:     annotation

app_modulo_sistema:
    resource: "@AppBundle/Controller/ModuloSistemaController.php"
    type:     annotation

app_dependencia:
    resource: "@AppBundle/Controller/DependenciaController.php"
    type:     annotation

usuario:
    resource: "@UsuarioBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


