jhweb_config_cfg_adm_acto_administrativo:
    resource: "@JHWEBConfigBundle/Controller/CfgAdmActoAdministrativoController.php"
    type:     annotation

jhweb_config_cfg_adm_formato:
    resource: "@JHWEBConfigBundle/Controller/CfgAdmFormatoController.php"
    type:     annotation

jhweb_config_cfg_adm_formato_tipo:
    resource: "@JHWEBConfigBundle/Controller/CfgAdmFormatoTipoController.php"
    type:     annotation

jhweb_contravencional:
    resource: "@JHWEBContravencionalBundle/Controller/"
    type:     annotation
    prefix:   /contravencional

jhweb_seguridad_vial:
    resource: "@JHWEBSeguridadVialBundle/Controller/"
    type:     annotation
    prefix:   /seguridadvial

jhweb_config:
    resource: "@JHWEBConfigBundle/Controller/"
    type:     annotation
    prefix:   /configuracion

jhweb_vehiculo:
    resource: "@JHWEBVehiculoBundle/Controller/"
    type:     annotation
    prefix:   /vehiculo
    
usuario:
    resource: "@UsuarioBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


