jhweb_usuario_user_empresa:
    resource: "@JHWEBUsuarioBundle/Controller/UserEmpresaController.php"
    type:     annotation

jhweb_usuario_user_ciudadano:
    resource: "@JHWEBUsuarioBundle/Controller/UserCiudadanoController.php"
    type:     annotation

jhweb_usuario_user_cfg_grupo_sanguineo:
    resource: "@JHWEBUsuarioBundle/Controller/UserCfgGrupoSanguineoController.php"
    type:     annotation

jhweb_usuario_user_cfg_genero:
    resource: "@JHWEBUsuarioBundle/Controller/UserCfgGeneroController.php"
    type:     annotation

jhweb_usuario_user_cfg_tipo_identificacion:
    resource: "@JHWEBUsuarioBundle/Controller/UserCfgTipoIdentificacionController.php"
    type:     annotation

jhweb_contravencional_cv_cdo_cfg_tipo_infractor:
    resource: "@JHWEBContravencionalBundle/Controller/CvCdoCfgTipoInfractorController.php"
    type:     annotation

jhweb_contravencional_cv_cdo_comparendo:
    resource: "@JHWEBContravencionalBundle/Controller/CvCdoComparendoController.php"
    type:     annotation

jhweb_vehiculo_vhlo_cfg_tipo_vehiculo:
    resource: "@JHWEBVehiculoBundle/Controller/VhloCfgTipoVehiculoController.php"
    type:     annotation

jhweb_banco_proyecto:
    resource: "@JHWEBBancoProyectoBundle/Controller/"
    type:     annotation
    prefix:   /bancoproyecto

jhweb_usuario:
    resource: "@JHWEBUsuarioBundle/Controller/"
    type:     annotation
    prefix:   /usuario

jhweb_financiero:
    resource: "@JHWEBFinancieroBundle/Controller/"
    type:     annotation
    prefix:   /financiero

jhweb_parqueadero:
    resource: "@JHWEBParqueaderoBundle/Controller/"
    type:     annotation
    prefix:   /parqueadero

jhweb_personal:
    resource: "@JHWEBPersonalBundle/Controller/"
    type:     annotation
    prefix:   /personal

jhweb_insumo:
    resource: "@JHWEBInsumoBundle/Controller/"
    type:     annotation
    prefix:   /insumo

jhweb_gestion_documental:
    resource: "@JHWEBGestionDocumentalBundle/Controller/"
    type:     annotation
    prefix:   /gestiondocumental

jhweb_contravencional:
    resource: "@JHWEBContravencionalBundle/Controller/"
    type:     annotation
    prefix:   /contravencional

jhweb_seguridad_vial:
    resource: "@JHWEBSeguridadVialBundle/Controller/"
    type:     annotation
    prefix:   /seguridadvial

jhweb_config:
    resource: "@JHWEBConfigBundle/Controller/"
    type:     annotation
    prefix:   /configuracion

jhweb_vehiculo:
    resource: "@JHWEBVehiculoBundle/Controller/"
    type:     annotation
    prefix:   /vehiculo
    
usuario:
    resource: "@UsuarioBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


