# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.jwt_auth:
      class:  AppBundle\services\JwtAuth
      arguments: ["@doctrine.orm.entity_manager"]

    app.helpers:
        class: AppBundle\services\Helpers
        arguments: ["@app.jwt_auth", '@doctrine.orm.entity_manager']

    app.gestion.documental:
        class: AppBundle\services\GestionDocumental
        autowire: false
        arguments: ['@doctrine.orm.entity_manager']

    app.pdf:
        class: AppBundle\services\PdfTemplate
        arguments: ["null"]

    app.pdf.factura:
        class: JHWEB\FinancieroBundle\Service\PdfTemplate
        arguments: ["null"]

    app.pdf.factura.membretes:
        class: JHWEB\FinancieroBundle\Service\PdfTemplateMembretes
        arguments: ["null"]

    app.pdf.insumo:
        class: JHWEB\InsumoBundle\Service\PdfTemplate
        arguments: ["null"]

    app.pdf.insumo.membretes:
        class: JHWEB\InsumoBundle\Service\PdfTemplateMembretes
        arguments: ["null"]    
