# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.jwt_auth:
      class:  AppBundle\services\JwtAuth
      arguments: ["@doctrine.orm.entity_manager"]

    app.helpers:
        class: AppBundle\services\Helpers
        arguments: ["@app.jwt_auth", '@doctrine.orm.entity_manager', "@app.mailer"]
    
    app.mailer:
        class: AppBundle\services\Mailer
        autowire: false
        arguments: ['@mailer', '@templating', '@session', '@doctrine.orm.entity_manager']

    app.gestion.documental:
        class: AppBundle\services\GestionDocumental
        autowire: false
        arguments: ['@doctrine.orm.entity_manager']

    app.pdf:
        class: AppBundle\services\PdfTemplate
        arguments: ["null"]

    app.pdf.certificado.tradicion:
        class: AppBundle\services\PdfTemplateCertificadoTradicion
        arguments: ["null"]

    app.pdf.factura:
        class: AppBundle\services\PdfTemplateFactura
        arguments: ["null"]

    app.excel:
        class: AppBundle\services\ExcelTemplate
        arguments: ['@doctrine.orm.entity_manager']

    app_soap:
        class: AppBundle\services\RecaudoService
        arguments: []

