# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.jwt_auth:
      class:  AppBundle\services\JwtAuth
      arguments: ["@doctrine.orm.entity_manager"]

    app.helpers:
        class: AppBundle\services\Helpers
        arguments: ["@app.jwt_auth"]

    app.gestion.documental:
        class: AppBundle\services\GestionDocumental
        autowire: false
        arguments: ['@doctrine.orm.entity_manager']