<?php

namespace JHWEB\BancoProyectoBundle\Repository;

/**
 * BpActividadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BpActividadRepository extends \Doctrine\ORM\EntityRepository
{
	//Obtiene la suma de los costos de actividades por proyecto
    public function getCostoTotalByCuenta($idCuenta)
    {
        $em = $this->getEntityManager();

        $dql = "SELECT SUM(a.costoTotal) AS total
            FROM JHWEBBancoProyectoBundle:BpActividad a
            WHERE a.cuenta = :idCuenta
            AND a.activo = true";
            
        $consulta = $em->createQuery($dql);

        $consulta->setParameter('idCuenta', $idCuenta);
        
        return $consulta->getOneOrNullResult();
    }
}
