<?php

namespace JHWEB\BancoProyectoBundle\Repository;

/**
 * BpActividadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BpActividadRepository extends \Doctrine\ORM\EntityRepository
{
	//Obtiene la suma de los costos de actividades por proyecto
    public function getCostoTotalByCuenta($idCuenta)
    {
        $em = $this->getEntityManager();

        $dql = "SELECT SUM(a.costoTotal) AS total
            FROM JHWEBBancoProyectoBundle:BpActividad a
            WHERE a.cuenta = :idCuenta
            AND a.activo = true";
            
        $consulta = $em->createQuery($dql);

        $consulta->setParameter('idCuenta', $idCuenta);
        
        return $consulta->getOneOrNullResult();
    }

    //Obtiene la suma de los costos de actividades por proyecto
    public function getByProyecto($idProyecto)
    {
        $em = $this->getEntityManager();

        $dql = "SELECT a
            FROM JHWEBBancoProyectoBundle:BpActividad a,
            JHWEBBancoProyectoBundle:BpCuenta c,
            JHWEBBancoProyectoBundle:BpProyecto p
            WHERE a.cuenta = c.id
            AND c.proyecto = p.id
            AND p.id = :idProyecto
            AND a.activo = true";
            
        $consulta = $em->createQuery($dql);

        $consulta->setParameter('idProyecto', $idProyecto);
        
        return $consulta->getResult();
    }
}
