<?php

namespace JHWEB\BancoProyectoBundle\Repository;

/**
 * BpCfgTipoInsumoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BpCfgTipoInsumoRepository extends \Doctrine\ORM\EntityRepository
{
}
