<?php

namespace JHWEB\BancoProyectoBundle\Repository;

/**
 * BpInsumoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BpInsumoRepository extends \Doctrine\ORM\EntityRepository
{
	//Obtiene la suma de los costos de isumos por actividad
    public function getCostoTotalByActividad($idActividad)
    {
        $em = $this->getEntityManager();

        $dql = "SELECT SUM(i.valorTotal) AS total
            FROM JHWEBBancoProyectoBundle:BpInsumo i
            WHERE i.actividad = :idActividad
            AND i.activo = true";
            
        $consulta = $em->createQuery($dql);

        $consulta->setParameter('idActividad', $idActividad);

        return $consulta->getOneOrNullResult();
    }
}
