<?php

namespace JHWEB\BancoProyectoBundle\Repository;

/**
 * BpInsumoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BpInsumoRepository extends \Doctrine\ORM\EntityRepository
{
}
