<?php

namespace JHWEB\BancoProyectoBundle\Repository;

/**
 * BpOrdenPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BpOrdenPagoRepository extends \Doctrine\ORM\EntityRepository
{
    //Obtiene el numero maximo de cdp por año
    public function getMaximo($anio)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT MAX(op.consecutivo) AS maximo
            FROM JHWEBBancoProyectoBundle:BpOrdenPago op
            WHERE YEAR(op.fecha) = :ANIO";
        $consulta = $em->createQuery($dql);
        $consulta->setParameter('ANIO', $anio);
        return $consulta->getOneOrNullResult();
    }
}
