<?php

namespace JHWEB\BancoProyectoBundle\Repository;

/**
 * BpOrdenPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BpOrdenPagoRepository extends \Doctrine\ORM\EntityRepository
{
    //Obtiene el numero maximo de cdp por año
    public function getMaximo($anio)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT MAX(op.consecutivo) AS maximo
            FROM JHWEBBancoProyectoBundle:BpOrdenPago op
            WHERE YEAR(op.fecha) = :ANIO";
        $consulta = $em->createQuery($dql);
        $consulta->setParameter('ANIO', $anio);
        return $consulta->getOneOrNullResult();
    }

    //Obtiene ordenes de pago por beneficiario
    public function getByBeneficiario($params)
    {
        $em = $this->getEntityManager();

        if ($params->idTipoIdentificacion != 4) {
            $dql = "SELECT o
            FROM JHWEBBancoProyectoBundle:BpOrdenPago o,
            JHWEBBancoProyectoBundle:BpRegistroCompromiso r,
            JHWEBUsuarioBundle:UserCiudadano c
            WHERE o.registroCompromiso = r.id
            AND r.ciudadano = c.id
            AND c.tipoIdentificacion = :idTipoIdentificacion
            AND c.identificacion = :identificacion
            AND o.activo = true";
        }else{
            $dql = "SELECT o
            FROM JHWEBBancoProyectoBundle:BpOrdenPago o,
            JHWEBBancoProyectoBundle:BpRegistroCompromiso r,
            JHWEBUsuarioBundle:UserEmpresa e
            WHERE o.registroCompromiso = r.id
            AND r.empresa = e.id
            AND e.tipoIdentificacion = :idTipoIdentificacion
            AND e.nit = :identificacion
            AND o.activo = true";
                
        }

        $consulta = $em->createQuery($dql);
        
        $consulta->setParameter('idTipoIdentificacion', $params->idTipoIdentificacion);
        $consulta->setParameter('identificacion', $params->identificacion);

        return $consulta->getResult();
    }

    //Obtiene las ordenes de pago por proyecto
    public function getOrdenesPagoByProyecto($idProyecto)
    {
        $em = $this->getEntityManager();

        $dql = "SELECT o
        FROM JHWEBBancoProyectoBundle:BpOrdenPago o,
        JHWEBBancoProyectoBundle:BpRegistroCompromiso r,
        JHWEBBancoProyectoBundle:BpCdp cdp,
        JHWEBBancoProyectoBundle:BpActividad a,
        JHWEBBancoProyectoBundle:BpCuenta c,
        JHWEBBancoProyectoBundle:BpProyecto p
        WHERE o.registroCompromiso = r.id
        AND r.cdp = cdp.id
        AND cdp.actividad = a.id
        AND a.cuenta = c.id
        AND c.proyecto = p.id
        AND p.id = :idProyecto
        AND p.activo = true";        

        $consulta = $em->createQuery($dql);

        $consulta->setParameter('idProyecto', $idProyecto);

        return $consulta->getResult();
    }
}
