<?php

namespace JHWEB\BancoProyectoBundle\Repository;

/**
 * BpOrdenPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BpOrdenPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
