<?php

namespace JHWEB\BancoProyectoBundle\Repository;

/**
 * BpProyectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BpProyectoRepository extends \Doctrine\ORM\EntityRepository
{
}
