<?php

namespace JHWEB\BancoProyectoBundle\Repository;

/**
 * BpReduccionCdpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BpReduccionCdpRepository extends \Doctrine\ORM\EntityRepository
{
}
