<?php

namespace JHWEB\BancoProyectoBundle\Repository;

/**
 * BpReduccionRegistroCompromisoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BpReduccionRegistroCompromisoRepository extends \Doctrine\ORM\EntityRepository
{
}
