<?php

namespace JHWEB\BancoProyectoBundle\Repository;

/**
 * BpReduccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BpReduccionRepository extends \Doctrine\ORM\EntityRepository
{
}
