<?php

namespace JHWEB\BancoProyectoBundle\Repository;

/**
 * BpRecursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BpRecursoRepository extends \Doctrine\ORM\EntityRepository
{
}
