<?php

namespace JHWEB\BancoProyectoBundle\Repository;

/**
 * BpRegistroCompromisoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BpRegistroCompromisoRepository extends \Doctrine\ORM\EntityRepository
{
    //Obtiene el numero maximo de cdp por año
    public function getMaximo($anio)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT MAX(c.solicitudConsecutivo) AS maximo
            FROM JHWEBBancoProyectoBundle:BpRegistroCompromiso c
            WHERE YEAR(c.solicitudFecha) = :ANIO";
        $consulta = $em->createQuery($dql);
        $consulta->setParameter('ANIO', $anio);
        return $consulta->getOneOrNullResult();
    }
}
