<?php

namespace JHWEB\ParqueaderoBundle\Repository;

/**
 * PqoCfgTarifaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PqoCfgTarifaRepository extends \Doctrine\ORM\EntityRepository
{
}
