<?php

namespace JHWEB\ParqueaderoBundle\Repository;

/**
 * PqoCfgGruaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PqoCfgGruaRepository extends \Doctrine\ORM\EntityRepository
{
}
