<?php

namespace JHWEB\ParqueaderoBundle\Repository;

/**
 * PqoCfgPatioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PqoCfgPatioRepository extends \Doctrine\ORM\EntityRepository
{
}
