<?php

namespace JHWEB\ParqueaderoBundle\Repository;

/**
 * PqoGruaCiudadanoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PqoGruaCiudadanoRepository extends \Doctrine\ORM\EntityRepository
{
}
