<?php

namespace JHWEB\ParqueaderoBundle\Repository;

/**
 * PqoInmovilizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PqoInmovilizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
