<?php

namespace JHWEB\ParqueaderoBundle\Repository;

/**
 * PqoPatioCiudadanoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PqoPatioCiudadanoRepository extends \Doctrine\ORM\EntityRepository
{
}
