<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvAuCfgHorarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvAuCfgHorarioRepository extends \Doctrine\ORM\EntityRepository
{
}
