<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvAuCfgTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvAuCfgTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
