<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvAuCfgAtencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvAuCfgAtencionRepository extends \Doctrine\ORM\EntityRepository
{
}
