<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvAudienciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvAudienciaRepository extends \Doctrine\ORM\EntityRepository
{
	//Obtiene las audiencias según el filtro de búsqueda
    public function getByFilter($params)
    {
        $em = $this->getEntityManager();

        switch ($params->tipoFiltro) {
            case 1:
                $dql = "SELECT a
                    FROM JHWEBContravencionalBundle:CvAudiencia a,
                    JHWEBContravencionalBundle:CvCdoComparendo c
                    WHERE a.comparendo = c.id
                    AND c.infractorIdentificacion = :identificacion";
                $consulta = $em->createQuery($dql);
                $consulta->setParameter('identificacion', $params->filtro);
                break;

            case 2:
                $dql = "SELECT a
                    FROM JHWEBContravencionalBundle:CvAudiencia a,
                    JHWEBContravencionalBundle:CvCdoComparendo c,
                    JHWEBPersonalBundle:PnalCfgCdoConsecutivo pc
                    WHERE a.comparendo = c.id
                    AND c.consecutivo = pc.id
                    AND pc.numero = :numero";
                $consulta = $em->createQuery($dql);
                $consulta->setParameter('numero', $params->filtro);
                break;

            case 3:
                $dql = "SELECT a
                    FROM JHWEBContravencionalBundle:CvAudiencia a,
                    JHWEBContravencionalBundle:CvCdoComparendo c
                    WHERE a.comparendo = c.id
                    AND a.fecha = :fecha";
                $consulta = $em->createQuery($dql);
                $consulta->setParameter('fecha', $params->filtro);
                break;
        }
        
        return $consulta->getResult();
    }

    //Obtiene la ultima audiencia programada
    public function getLast()
    {
        $em = $this->getEntityManager();
        $dql = "SELECT MAX(a.fecha) AS fecha, a.id AS id
            FROM JHWEBContravencionalBundle:CvAudiencia a
            WHERE a.activo = true";
        $consulta = $em->createQuery($dql);

        return $consulta->getOneOrNullResult();
    }
}
