<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvAudienciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvAudienciaRepository extends \Doctrine\ORM\EntityRepository
{
}
