<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvAuEstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvAuEstadoRepository extends \Doctrine\ORM\EntityRepository
{
}
