<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvCcCfgRecordatorioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCcCfgRecordatorioRepository extends \Doctrine\ORM\EntityRepository
{
}
