<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvCcNotificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCcNotificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
