<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvCdoTrazabilidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCdoTrazabilidadRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByComparendo($idComparendo){
        $em = $this->getEntityManager();

        $dql = "SELECT t
        FROM JHWEBContravencionalBundle:CvCdoTrazabilidad t,
        JHWEBContravencionalBundle:CvCdoComparendo c
        WHERE t.comparendo = c.id
        AND t.comparendo = :idComparendo
        ORDER BY t.fecha DESC, t.hora DESC";

        $consulta = $em->createQuery($dql);
        $consulta->setParameters(array(
            'idComparendo' => $idComparendo,
        ));

        return $consulta->getResult();
    }

    public function getNotificationWeb($type, $value){
        $em = $this->getEntityManager();

        switch ($type) {
            case 'identificacion':
                $dql = "SELECT t
                FROM JHWEBContravencionalBundle:CvCdoTrazabilidad t,
                JHWEBContravencionalBundle:CvCdoComparendo c
                WHERE t.comparendo = c.id
                AND t.estado = 22
                AND c.infractorIdentificacion = :identificacion";

                $consulta = $em->createQuery($dql);
                $consulta->setParameters(array(
                    'identificacion' => $value,
                ));

                break;
        }

        return $consulta->getResult();
    }
}
