<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvCdoComparendoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCdoComparendoRepository extends \Doctrine\ORM\EntityRepository
{
}
