<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvCdoCfgTipoInfractorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCdoCfgTipoInfractorRepository extends \Doctrine\ORM\EntityRepository
{
}
