<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvCdoCursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCdoCursoRepository extends \Doctrine\ORM\EntityRepository
{
}
