<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvCdoCfgEstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCdoCfgEstadoRepository extends \Doctrine\ORM\EntityRepository
{
}
