<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvCdoCfgDescuentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCdoCfgDescuentoRepository extends \Doctrine\ORM\EntityRepository
{
}
