<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvCdoNotificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCdoNotificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
