<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvCdoTrazabilidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCdoTrazabilidadRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByComparendo($idComparendo){
        $em = $this->getEntityManager();

        $dql = "SELECT t
        FROM JHWEBContravencionalBundle:CvCdoTrazabilidad t,
        JHWEBContravencionalBundle:CvCdoComparendo c
        WHERE t.comparendo = c.id
        AND t.comparendo = :idComparendo
        ORDER BY t.fecha DESC, t.hora DESC";

        $consulta = $em->createQuery($dql);
        $consulta->setParameters(array(
            'idComparendo' => $idComparendo,
        ));

        return $consulta->getResult();
    }

    public function getNotificationWeb($type, $value){
        $em = $this->getEntityManager();

        switch ($type) {
            case 'identificacion':
                $dql = "SELECT t
                FROM JHWEBContravencionalBundle:CvCdoTrazabilidad t,
                JHWEBContravencionalBundle:CvCdoComparendo c
                WHERE t.comparendo = c.id
                AND t.estado = 22
                AND c.infractorIdentificacion = :identificacion";

                $consulta = $em->createQuery($dql);
                $consulta->setParameters(array(
                    'identificacion' => $value,
                ));

                break;
        }

        return $consulta->getResult();
    }

    //Obtiene todos los vehiculos del módulo RNA entre fechas para creación de archivo plano
    public function getResolucionesByFechasForLicenciasConduccion($fechaInicial, $fechaFinal)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT ct
            FROM JHWEBContravencionalBundle:CvCdoTrazabilidad ct,
            JHWEBContravencionalBundle:CvCdoComparendo c,
            JHWEBContravencionalBundle:CvCdoCfgEstado ce
            WHERE ct.comparendo = c.id
            AND c.fecha BETWEEN :fechaInicial AND :fechaFinal
            AND c.activo = true
            AND ce.activo = true
            AND ct.estado = ce.id
            AND (ce.codigo = 13 OR ce.codigo = 7)";

        $consulta = $em->createQuery($dql);

        $consulta->setParameters(array(
            'fechaInicial' => $fechaInicial,
            'fechaFinal' => $fechaFinal
        ));
        
        return $consulta->getResult();
    }
}
