<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvCdoCfgInteresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCdoCfgInteresRepository extends \Doctrine\ORM\EntityRepository
{
}
