<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvCdoSeguimientoEntregaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCdoSeguimientoEntregaRepository extends \Doctrine\ORM\EntityRepository
{
}
