<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvCfgModuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCfgModuloRepository extends \Doctrine\ORM\EntityRepository
{
}
