<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvCfgMotivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCfgMotivoRepository extends \Doctrine\ORM\EntityRepository
{
}
