<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvCfgRestriccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCfgRestriccionRepository extends \Doctrine\ORM\EntityRepository
{
}
