<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvCfgTipoRestriccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCfgTipoRestriccionRepository extends \Doctrine\ORM\EntityRepository
{
}
