<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvCfgPorcentajeInicialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCfgPorcentajeInicialRepository extends \Doctrine\ORM\EntityRepository
{
}
