<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvCfgInteresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCfgInteresRepository extends \Doctrine\ORM\EntityRepository
{
}
