<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvCfgTipoMedidaCautelarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCfgTipoMedidaCautelarRepository extends \Doctrine\ORM\EntityRepository
{
}
