<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvCfgRepartoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvCfgRepartoRepository extends \Doctrine\ORM\EntityRepository
{
}
