<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvComparendoNotificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvComparendoNotificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
