<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvInvestigacionBienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvInvestigacionBienRepository extends \Doctrine\ORM\EntityRepository
{
}
