<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvInventarioDocumentalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvInventarioDocumentalRepository extends \Doctrine\ORM\EntityRepository
{
}
