<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvLcRetencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvLcRetencionRepository extends \Doctrine\ORM\EntityRepository
{
}
