<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvLcCfgMotivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvLcCfgMotivoRepository extends \Doctrine\ORM\EntityRepository
{
}
