<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvLcCfgRestriccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvLcCfgRestriccionRepository extends \Doctrine\ORM\EntityRepository
{
}
