<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvLcCfgTipoRestriccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvLcCfgTipoRestriccionRepository extends \Doctrine\ORM\EntityRepository
{
}
