<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvMedidaCautelarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvMedidaCautelarRepository extends \Doctrine\ORM\EntityRepository
{
}
