<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvNotificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvNotificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
