<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvRecaudoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvRecaudoRepository extends \Doctrine\ORM\EntityRepository
{
}
