<?php

namespace JHWEB\ContravencionalBundle\Repository;

/**
 * CvRestriccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvRestriccionRepository extends \Doctrine\ORM\EntityRepository
{
}
