<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCapacitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCapacitacionRepository extends \Doctrine\ORM\EntityRepository
{
}
