<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCaracterizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCaracterizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
