<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCalificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCalificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
