<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgClaseActorViaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgClaseActorViaRepository extends \Doctrine\ORM\EntityRepository
{
}
