<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgFuncionCriterioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgFuncionCriterioRepository extends \Doctrine\ORM\EntityRepository
{
}
