<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgSenialTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgSenialTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
