<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgCriterioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgCriterioRepository extends \Doctrine\ORM\EntityRepository
{
}
