<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgEducacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgEducacionRepository extends \Doctrine\ORM\EntityRepository
{
}
