<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgGravedadAccidenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgGravedadAccidenteRepository extends \Doctrine\ORM\EntityRepository
{
}
