<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgSenialColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgSenialColorRepository extends \Doctrine\ORM\EntityRepository
{
}
