<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgSenialUnidadMedidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgSenialUnidadMedidaRepository extends \Doctrine\ORM\EntityRepository
{
}
