<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgSenialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgSenialRepository extends \Doctrine\ORM\EntityRepository
{
}
