<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgSolidaridadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgSolidaridadRepository extends \Doctrine\ORM\EntityRepository
{
}
