<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgTemaCapacitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgTemaCapacitacionRepository extends \Doctrine\ORM\EntityRepository
{
}
