<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgEntidadAccidenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgEntidadAccidenteRepository extends \Doctrine\ORM\EntityRepository
{
}
