<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgHipotesisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgHipotesisRepository extends \Doctrine\ORM\EntityRepository
{
}
