<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgDisenioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgDisenioRepository extends \Doctrine\ORM\EntityRepository
{
}
