<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgVisualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgVisualRepository extends \Doctrine\ORM\EntityRepository
{
}
