<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgTipoViaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgTipoViaRepository extends \Doctrine\ORM\EntityRepository
{
}
