<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgPreventivaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgPreventivaRepository extends \Doctrine\ORM\EntityRepository
{
}
