<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgSustanciaPeligrosaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgSustanciaPeligrosaRepository extends \Doctrine\ORM\EntityRepository
{
}
