<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgNacionalidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgNacionalidadRepository extends \Doctrine\ORM\EntityRepository
{
}
