<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgClaseAccidenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgClaseAccidenteRepository extends \Doctrine\ORM\EntityRepository
{
}
