<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
