<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgGradoExamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgGradoExamenRepository extends \Doctrine\ORM\EntityRepository
{
}
