<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgIluminacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgIluminacionRepository extends \Doctrine\ORM\EntityRepository
{
}
