<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgAsistenciaCivicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgAsistenciaCivicaRepository extends \Doctrine\ORM\EntityRepository
{
}
