<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgSenialEstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgSenialEstadoRepository extends \Doctrine\ORM\EntityRepository
{
}
