<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgSeguridadCiudadanaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgSeguridadCiudadanaRepository extends \Doctrine\ORM\EntityRepository
{
}
