<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgTipoVictimaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgTipoVictimaRepository extends \Doctrine\ORM\EntityRepository
{
}
