<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgUnidadReceptoraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgUnidadReceptoraRepository extends \Doctrine\ORM\EntityRepository
{
}
