<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgEstadoConductorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgEstadoConductorRepository extends \Doctrine\ORM\EntityRepository
{
}
