<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgCondicionViaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgCondicionViaRepository extends \Doctrine\ORM\EntityRepository
{
}
