<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgCardinalidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgCardinalidadRepository extends \Doctrine\ORM\EntityRepository
{
}
