<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgEstadoViaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgEstadoViaRepository extends \Doctrine\ORM\EntityRepository
{
}
