<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgObjetoFijoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgObjetoFijoRepository extends \Doctrine\ORM\EntityRepository
{
}
