<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgUtilizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgUtilizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
