<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgFallaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgFallaRepository extends \Doctrine\ORM\EntityRepository
{
}
