<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgSectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgSectorRepository extends \Doctrine\ORM\EntityRepository
{
}
