<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgControlesTransitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgControlesTransitoRepository extends \Doctrine\ORM\EntityRepository
{
}
