<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgLugarImpactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgLugarImpactoRepository extends \Doctrine\ORM\EntityRepository
{
}
