<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgVariableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgVariableRepository extends \Doctrine\ORM\EntityRepository
{
}
