<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgRequiereEmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgRequiereEmpresaRepository extends \Doctrine\ORM\EntityRepository
{
}
