<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgClaseChoqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgClaseChoqueRepository extends \Doctrine\ORM\EntityRepository
{
}
