<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgTipoControlesTransitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgTipoControlesTransitoRepository extends \Doctrine\ORM\EntityRepository
{
}
