<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgTipoAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgTipoAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
