<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgMotivoAnulacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgMotivoAnulacionRepository extends \Doctrine\ORM\EntityRepository
{
}
