<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgFuncionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgFuncionRepository extends \Doctrine\ORM\EntityRepository
{
}
