<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgTipoControlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgTipoControlRepository extends \Doctrine\ORM\EntityRepository
{
}
