<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgTipoGeometriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgTipoGeometriaRepository extends \Doctrine\ORM\EntityRepository
{
}
