<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgVisualDisminuidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgVisualDisminuidaRepository extends \Doctrine\ORM\EntityRepository
{
}
