<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgLineaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgLineaRepository extends \Doctrine\ORM\EntityRepository
{
}
