<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgSenialLineaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgSenialLineaRepository extends \Doctrine\ORM\EntityRepository
{
}
