<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgControlViaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgControlViaRepository extends \Doctrine\ORM\EntityRepository
{
}
