<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgEstadoIluminacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgEstadoIluminacionRepository extends \Doctrine\ORM\EntityRepository
{
}
