<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgGravedadVictimaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgGravedadVictimaRepository extends \Doctrine\ORM\EntityRepository
{
}
