<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgPoliciaJudicialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgPoliciaJudicialRepository extends \Doctrine\ORM\EntityRepository
{
}
