<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgZonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgZonaRepository extends \Doctrine\ORM\EntityRepository
{
}
