<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgCategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgCategoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
