<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgCalzadaCarrilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgCalzadaCarrilRepository extends \Doctrine\ORM\EntityRepository
{
}
