<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgAseguradoraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgAseguradoraRepository extends \Doctrine\ORM\EntityRepository
{
}
