<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgMaterialRepository extends \Doctrine\ORM\EntityRepository
{
}
