<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgEstadoTiempoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgEstadoTiempoRepository extends \Doctrine\ORM\EntityRepository
{
}
