<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgParametroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgParametroRepository extends \Doctrine\ORM\EntityRepository
{
}
