<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgHospitalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgHospitalRepository extends \Doctrine\ORM\EntityRepository
{
}
