<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgGeometriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgGeometriaRepository extends \Doctrine\ORM\EntityRepository
{
}
