<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgTipoSenialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgTipoSenialRepository extends \Doctrine\ORM\EntityRepository
{
}
