<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvCfgResultadoExamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvCfgResultadoExamenRepository extends \Doctrine\ORM\EntityRepository
{
}
