<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvEvaluacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvEvaluacionRepository extends \Doctrine\ORM\EntityRepository
{
}
