<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvIpatImpresoBodegaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvIpatImpresoBodegaRepository extends \Doctrine\ORM\EntityRepository
{
    //Obtiene el total de impresos disponibles por organismo de tránsito
    public function getTotalDisponible()
    { 
        $em = $this->getEntityManager();
        $dql = "SELECT SUM(b.cantidadDisponible) AS cantidad
            FROM JHWEBSeguridadVialBundle:SvIpatImpresoBodega b
            WHERE b.activo = true
            AND b.estado = 'DISPONIBLE'";

        $consulta = $em->createQuery($dql);
        
        return $consulta->getOneOrNullResult();
    }
}
