<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvIpatOrganismoTransitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvIpatOrganismoTransitoRepository extends \Doctrine\ORM\EntityRepository
{
}
