<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvIpatVictimaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvIpatVictimaRepository extends \Doctrine\ORM\EntityRepository
{
}
