<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvIpatVehiculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvIpatVehiculoRepository extends \Doctrine\ORM\EntityRepository
{
}
