<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvIpatTalonarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvIpatTalonarioRepository extends \Doctrine\ORM\EntityRepository
{
}
