<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvIpatConductorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvIpatConductorRepository extends \Doctrine\ORM\EntityRepository
{
}
