<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvIpatImpresoMunicipioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvIpatImpresoMunicipioRepository extends \Doctrine\ORM\EntityRepository
{
}
