<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvIpatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvIpatRepository extends \Doctrine\ORM\EntityRepository
{
    public function getIpatByRango($params) {

        $em = $this->getEntityManager();

        $condicion = null; 

        $horaInicio = $params->datos->horaInicio;
        $horaFin = $params->datos->horaFin;
        $fechaInicio = $params->datos->fechaInicio;
        $fechaFin = $params->datos->fechaFin;
        
        $dql = "SELECT i
            FROM JHWEBSeguridadVialBundle:SvIpat i, JHWEBSeguridadVialBundle:SvIpatVictima iv,
            JHWEBSeguridadVialBundle:SvIpatConductor ic, JHWEBSeguridadVialBundle:SvIpatVehiculo ive
            WHERE i.activo = 1";

        if($params->datos->arrayGravedadAccidente){
            foreach ($params->datos->arrayGravedadAccidente as $keyGravedad => $idGravedad) {
                if($keyGravedad == 0){
                    $condicion .= " AND i.gravedadAccidente = '" . $idGravedad . "'";
                } else {
                    $condicion .= " OR i.gravedadAccidente = '" . $idGravedad . "'";
                }
            }
        }

        if($params->datos->arrayTipoVictima){
            foreach ($params->datos->arrayTipoVictima as $keyTipoVictima => $idTipoVictima) {          
                if($keyTipoVictima == 0) {
                    $condicion .= " AND iv.tipoVictima = '" . $idTipoVictima . "'";
                }
                else {
                    $condicion .= " OR iv.tipoVictima = '" . $idTipoVictima . "'";
                }
            }
        }
        /* if($horaInicio && $horaFin){
            
            $condicion .= " AND i.horaAccidente BETWEEN " . $horaInicio . " AND $horaFin";
        } */

        if($fechaInicio && $fechaFin){
            $condicion .= " AND i.fechaAccidente BETWEEN " . $fechaInicio . " AND $fechaFin";
        }

        if ($params->datos->arrayGrupoEdad) {
            foreach ($params->datos->arrayGrupoEdad as $keyGrupoEdad => $idGrupoEdad) {
                # code...
                $edadInicio = intval($idGrupoEdad);
                $edadFin = $edadInicio + 4;

                if($keyGrupoEdad == 0) {
                    $condicion .= " AND iv.edad BETWEEN " . $edadInicio . " AND $edadFin";
                    $condicion .= " AND ic.edad BETWEEN " . $edadInicio . " AND $edadFin";
                } else {
                    $condicion .= " OR iv.edad BETWEEN " . $edadInicio . " AND $edadFin";
                    $condicion .= " OR ic.edad BETWEEN " . $edadInicio . " AND $edadFin";
                }
            }
        }

        if($params->datos->arrayMunicipio) {
            foreach ($params->datos->arrayMunicipio as $keyMunicipio => $idMunicipio) {
                # code...
                $municipio = $em->getRepository('JHWEBConfigBundle:CfgMunicipio')->find($idMunicipio);

                if($keyMunicipio == 0) {
                    $condicion .= " AND ic.ciudadResidencia = '" . $municipio->getNombre() . "'";
                    $condicion .= " AND iv.ciudadResidencia = '" . $municipio->getNombre() . "'";
                }
                else {
                    $condicion .= " OR ic.ciudadResidencia = '" . $municipio->getNombre() . "'";
                    $condicion .= " OR iv.ciudadResidencia = '" . $municipio->getNombre() . "'";
                }
            }
        }

        if($params->datos->arrayDiaSemana) {
            foreach ($params->datos->arrayDiaSemana as $keyDiaSemana => $diaSemana) {
                # code...
                if($keyDiaSemana == 0) {
                    $condicion .= " AND i.diaAccidente = '" . $diaSemana . "'";
                }
                else {
                    $condicion .= " OR i.diaAccidente = '" . $diaSemana . "'";
                }
            }
        } 

        if($params->datos->arrayGenero) {
            foreach ($params->datos->arrayGenero as $keyGenero => $idGenero) {
                # code...
                $genero = $em->getRepository('JHWEBUsuarioBundle:UserCfgGenero')->find($idGenero);

                if($keyGenero == 0) {
                    $condicion .= " AND ic.sexo = '" . $genero->getSigla() . "'";
                    $condicion .= " AND iv.sexo = '" . $genero->getSigla() . "'";
                }
                else {
                    $condicion .= " OR ic.sexo = '" . $genero->getSigla() . "'";
                    $condicion .= " OR iv.sexo = '" . $genero->getSigla() . "'";
                }
            }
        }

        if ($params->datos->arrayClase) {
            foreach ($params->datos->arrayClase as $keyClase => $idClase) {
                # code...
                $clase = $em->getRepository('JHWEBVehiculoBundle:VhloCfgClase')->find($idClase);
                if($keyClase == 0) {
                    $condicion .= " AND ive.clase = '" . $clase->getNombre() . "'";
                }
                else {
                    $condicion .= " OR ive.clase = '" . $clase->getNombre() . "'";
                }
            }
        }

        if($params->datos->arrayClaseAccidente){
            foreach ($params->datos->arrayClaseAccidente as $keyClaseAccidente => $idClaseAccidente) {
                # code...
                if($keyClaseAccidente == 0) {
                    $condicion .= " AND i.claseAccidente = '" . $idClaseAccidente . "'";
                }
                else {
                    $condicion .= " OR i.claseAccidente = '" . $idClaseAccidente . "'";
                }
            }
        }

        if($params->datos->arrayClaseChoque) {
            foreach ($params->datos->arrayClaseChoque as $keyClaseChoque => $idClaseChoque) {
                # code...
                if($keyClaseChoque == 0) {
                    $condicion .= " AND i.claseChoque = '" . $idClaseChoque . "'";
                }
                else {
                    $condicion .= " OR i.claseChoque = '" . $idClaseChoque . "'";
                }
            } 
        }

        if($params->datos->arrayObjetoFijo) {
            foreach ($params->datos->arrayObjetoFijo as $keyObjetoFijo => $idObjetoFijo) {
                # code...
                if($keyObjetoFijo == 0) {
                    $condicion .= " AND i.objetoFijo = '" . $idObjetoFijo . "'";
                }
                else {
                    $condicion .= " OR i.objetoFijo = '" . $idObjetoFijo . "'";
                }
            }
        }
        //=====================
        if ($condicion) {
            $dql .= $condicion;
        }

        $consulta = $em->createQuery($dql);

        return $consulta->getResult();
    }
}
