<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvIpatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvIpatRepository extends \Doctrine\ORM\EntityRepository
{
}
