<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvIpatConsecutivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvIpatConsecutivoRepository extends \Doctrine\ORM\EntityRepository
{
}
