<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvIpatImpresoAsignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvIpatImpresoAsignacionRepository extends \Doctrine\ORM\EntityRepository
{
}
