<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvIpatImpresoAsignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvIpatImpresoAsignacionRepository extends \Doctrine\ORM\EntityRepository
{
    //Obtiene el numero maximo de asignaciones por año
    public function getMaximo($anio)
    {
        $em = $this->getEntityManager();
        
        $dql = "SELECT MAX(a.consecutivo) AS maximo
            FROM JHWEBSeguridadVialBundle:SvIpatImpresoAsignacion a
            WHERE YEAR(a.fecha) = :ANIO";

        $consulta = $em->createQuery($dql);
        $consulta->setParameter('ANIO', $anio);

        return $consulta->getOneOrNullResult();
    }

    //Obtiene el total de impresos disponibles por organismo de tránsito
    public function getTotalDisponibleByOrganismoTransito($idOrganismoTransito)
    { 
        $em = $this->getEntityManager();
        $dql = "SELECT SUM(a.cantidadDisponible) AS cantidad
            FROM JHWEBSeguridadVialBundle:SvIpatImpresoAsignacion a
            WHERE a.activo = true
            AND a.organismoTransito = :organismoTransito
            GROUP BY a.organismoTransito";

        $consulta = $em->createQuery($dql);
        $consulta->setParameters(array(
            'organismoTransito' => $idOrganismoTransito,
        ));
        
        return $consulta->getOneOrNullResult();
    }
}
