<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvIpatAsignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvIpatAsignacionRepository extends \Doctrine\ORM\EntityRepository
{
}
