<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvIpatImpresoBodegaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvIpatImpresoBodegaRepository extends \Doctrine\ORM\EntityRepository
{
}
