<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvRevisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvRevisionRepository extends \Doctrine\ORM\EntityRepository
{
    //Obtiene el numero maximo de documentos por año
    public function getMaximo($anio)
    {
        $em = $this->getEntityManager();
        
        $dql = "SELECT MAX(r.consecutivo) AS maximo
            FROM AppBundle:MsvRevision r
            WHERE YEAR(r.fechaRegistro) = :ANIO";
        $consulta = $em->createQuery($dql);
        $consulta->setParameter('ANIO', $anio);
        return $consulta->getOneOrNullResult();
    }
}
