<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvRegistroIpatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvRegistroIpatRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByRango($params) {
        $horaInicioDatetime = new \Datetime($params->horaInicio);
        $horaFinDatetime = new \Datetime($params->horaFin);
        $fechaInicioDatetime = new \Datetime($params->fechaInicio);
        $fechaFinDatetime = new \Datetime($params->fechaFin);
    }
}
