<?php

namespace JHWEB\SeguridadVialBundle\Repository;

use JHWEB\SeguridadVialBundle\Entity\SvRegistroIpat;

/**
 * SvRegistroIpatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvRegistroIpatRepository extends \Doctrine\ORM\EntityRepository
{

    public function getIpatByRango($params) {
        $em = $this->getEntityManager();

        $condicion = null; 

        $horaInicioDatetime = $params->datos->horaInicio;
        $horaFinDatetime = $params->datos->horaFin;
        $fechaInicioDatetime = new \Datetime($params->datos->fechaInicio);
        $fechaFinDatetime = new \Datetime($params->datos->fechaFin);
    
        var_dump($params);
        die();
        
        foreach ($params->datos->arrayGravedadAccidente as $key => $idGravedad) {
            # code...
            $gravedadAccidente = $em->getRepository('JHWEBSeguridadVialBundle:SvCfgGravedadAccidente')->find($idGravedad);
            $condicion .= " OR ri.gravedadAccidente = '" . $gravedadAccidente . "'";
        }
        
        foreach ($params->datos->idTipoVictima as $key => $arrayTipoVictima) {
            # code...
        }
        /* if ($params->datos->idGravedad) {
            $gravedadAccidente = $em->getRepository('JHWEBSeguridadVialBundle:SvCfgGravedadAccidente')->find($params->datos->idGravedad);
        }
        if ($params->datos->idTipoVictima) {
            $tipoVictima = $em->getRepository('JHWEBSeguridadVialBundle:SvCfgTipoVictima')->findBy(
                array(
                    'nombre' => $params->datos->idTipoVictima,
                )
            );
        }
        if ($params->datos->idMunicipio) {
            $municipio = $em->getRepository('JHWEBConfigBundle:CfgMunicipio')->find($params->datos->idMunicipio);
        }
        $municipioNombre = $municipio->getNombre();

        if ($params->datos->idGenero) {
            $genero = $em->getRepository('JHWEBUsuarioBundle:UserCfgGenero')->find($params->datos->idGenero);
        }
        $sexoConductor = $genero->getSigla();

        if ($params->datos->idClase) {
            $clase = $em->getRepository('JHWEBVehiculoBundle:VhloCfgClase')->find($params->datos->idClase);
        }
        $claseNombre = $clase->getNombre();

        if ($params->datos->idClaseAccidente) {
            $claseAccidente = $em->getRepository('JHWEBSeguridadVialBundle:SvCfgClaseAccidente')->findBy(
                array(
                    'nombre' => $params->datos->idClaseAccidente,
                )
            );
        }
        if ($params->datos->idChoqueCon) {
            $choqueCon = $em->getRepository('AppBundle:CfgChoqueCon')->findBy(
                array(
                    'nombre' => $params->datos->idChoqueCon,
                )
            );
        }
        if ($params->datos->idObjetoFijo) {
            $objetoFijo = $em->getRepository('AppBundle:CfgObjetoFijo')->find($params->datos->idObjetoFijo);
        }
        
        $edadInicioConductor = intval($params->datos->idGrupoEdad);
        $edadFinConductor = $edadInicioConductor + 4;
        $diaAccidente = $params->datos->idDiaSemana; */

        $dql = "SELECT ri
            FROM JHWEBSeguridadVialBundle:SvRegistroIpat ri
            WHERE ri.gravedadAccidente = :gravedadAccidente
            AND ri.activo = 1";
        
        $consulta = $em->createQuery($dql);
        $consulta->setParameters(array(
            'gravedadAccidente' => $gravedadAccidente,
        ));

        return $consulta->getResult();
    } 
}
