<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvRegistroIpatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvRegistroIpatRepository extends \Doctrine\ORM\EntityRepository
{
}
