<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvSenialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvSenialRepository extends \Doctrine\ORM\EntityRepository
{
}
