<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvSenialInventarioBodegaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvSenialInventarioBodegaRepository extends \Doctrine\ORM\EntityRepository
{
	//Obtiene el numero maximo de las solicitudes
    public function findMaximo($anio)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT MAX(si.consecutivo) AS maximo
            FROM JHWEBSeguridadVialBundle:SvSenialInventarioBodega si
            WHERE YEAR(si.fecha) = :ANIO";
        $consulta = $em->createQuery($dql);
        $consulta->setParameter('ANIO', $anio);
        return $consulta->getOneOrNullResult();
    }
}
