<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvSenialUbicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvSenialUbicacionRepository extends \Doctrine\ORM\EntityRepository
{
}
