<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvSenialInventarioMunicipioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvSenialInventarioMunicipioRepository extends \Doctrine\ORM\EntityRepository
{
}
