<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvSenialTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvSenialTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
