<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvSenialDemarcacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvSenialDemarcacionRepository extends \Doctrine\ORM\EntityRepository
{
}
