<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvSenialUbicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvSenialUbicacionRepository extends \Doctrine\ORM\EntityRepository
{
	//Obtiene las seniales por senial
    public function getBySenial($idSenial)
    {
        $em = $this->getEntityManager();

        $dql = "SELECT su
        FROM JHWEBSeguridadVialBundle:SvSenialUbicacion su,
        JHWEBSeguridadVialBundle:SvCfgSenialTipo st,
        JHWEBSeguridadVialBundle:SvCfgSenial s,
        JHWEBSeguridadVialBundle:SvCfgSenialProveedor sp
        WHERE su.senial = :idSenial
        AND su.senial = s.id
        AND s.tipoSenial = st.id";

        $consulta = $em->createQuery($dql);

        $consulta->setParameters(array(
           'idSenial' => $idSenial,
        ));
        

        return $consulta->getResult();
    }

    public function getByFechas($params){
        $em = $this->getEntityManager();

        $dql = "SELECT u
        FROM JHWEBSeguridadVialBundle:SvSenialUbicacion u, 
        JHWEBSeguridadVialBundle:SvCfgSenial s,
        JHWEBSeguridadVialBundle:SvCfgSenialTipo t
        WHERE u.fecha BETWEEN :fechaInicial AND :fechaFinal
        AND u.municipio = :idMunicipio
        AND u.senial = s.id
        AND s.tipoSenial = t.id
        AND t.id != 1";

        $consulta = $em->createQuery($dql);
        $consulta->setParameters(array(
            'fechaInicial' => $params->fechaInicial,
            'fechaFinal' => $params->fechaFinal,
            'idMunicipio' => $params->idMunicipio,
        ));

        return $consulta->getResult();
    }
}
