<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvSenialLineaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvSenialLineaRepository extends \Doctrine\ORM\EntityRepository
{
}
