<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvSenialEstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvSenialEstadoRepository extends \Doctrine\ORM\EntityRepository
{
}
