<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvSenialBodegaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvSenialBodegaRepository extends \Doctrine\ORM\EntityRepository
{
}
