<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvSenialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvSenialRepository extends \Doctrine\ORM\EntityRepository
{
	//Obtiene las señales por tipo de señal en inventario de bodega
    public function getByTipoSenial($idTipoSenial)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT s
            FROM JHWEBSeguridadVialBundle:SvSenialInventarioBodega sib,
            JHWEBSeguridadVialBundle:SvSenial s
            WHERE s.inventario = sib.id
            AND sib.tipoSenial = :idTipoSenial";
        $consulta = $em->createQuery($dql);
        $consulta->setParameter('idTipoSenial', $idTipoSenial);
        return $consulta->getResult();
    }
}
