<?php

namespace JHWEB\ConfigBundle\Repository;

/**
 * SvSenialInventarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvSenialInventarioRepository extends \Doctrine\ORM\EntityRepository
{
}
