<?php

namespace JHWEB\SeguridadVialBundle\Repository;

/**
 * SvSenialColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvSenialColorRepository extends \Doctrine\ORM\EntityRepository
{
}
