<?php

namespace JHWEB\GestionDocumentalBundle\Repository;

/**
 * GdCfgMedioCorrespondenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GdCfgMedioCorrespondenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
