<?php

namespace JHWEB\GestionDocumentalBundle\Repository;

/**
 * GdCfgTipoCorrespondenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GdCfgTipoCorrespondenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
