<?php

namespace JHWEB\GestionDocumentalBundle\Repository;

/**
 * GdCfgSeccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GdCfgSeccionRepository extends \Doctrine\ORM\EntityRepository
{
}
