<?php

namespace JHWEB\GestionDocumentalBundle\Repository;

/**
 * GdDocumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GdDocumentoRepository extends \Doctrine\ORM\EntityRepository
{
	//Obtiene el numero maximo de documentos por año
    public function getMaximo($anio)
    {
        $em = $this->getEntityManager();
        
        $dql = "SELECT MAX(d.consecutivo) AS maximo
            FROM JHWEBGestionDocumentalBundle:GdDocumento d
            WHERE YEAR(d.fechaRegistro) = :ANIO";
        $consulta = $em->createQuery($dql);
        $consulta->setParameter('ANIO', $anio);
        return $consulta->getOneOrNullResult();
    }

	//Obtiene la lista de documentos por tipo de filtro
    public function getByFilter($params){  
        $em = $this->getEntityManager();

        switch ($params->tipoFiltro) {
            case 1:
                $dql = "SELECT d
                FROM JHWEBGestionDocumentalBundle:GdDocumento d
                WHERE d.peticionarioNombres LIKE :nombres
                OR d.peticionarioNombres LIKE :apellidos";

                $consulta = $em->createQuery($dql);
                $consulta->setParameters(array(
                    'nombres' => '%'.$params->filtro.'%',
                    'apellidos' => '%'.$params->filtro.'%',
                ));
                break;

            case 2:
                $dql = "SELECT d
                FROM JHWEBGestionDocumentalBundle:GdDocumento d
                WHERE d.identificacion = :identificacion";

                $consulta = $em->createQuery($dql);
                $consulta->setParameters(array(
                    'identificacion' => $params->filtro,
                ));
                break;

            case 3:
                $dql = "SELECT d
                FROM JHWEBGestionDocumentalBundle:GdDocumento d
                WHERE d.entidadNombre LIKE :entidadNombre";

                $consulta = $em->createQuery($dql);
                $consulta->setParameters(array(
                    'entidadNombre' => '%'.$params->filtro.'%',
                ));
                break;

            case 4:
                $dql = "SELECT d
                FROM JHWEBGestionDocumentalBundle:GdDocumento d
                WHERE d.numeroRadicado = :numeroRadicado";

                $consulta = $em->createQuery($dql);
                $consulta->setParameters(array(
                    'numeroRadicado' => $params->filtro,
                ));
                break;
        }

        return $consulta->getResult();
    }

    //Obtiene los documentos entre fechas
    public function getByDates($fechaInicial, $fechaFinal)
    {
        $em = $this->getEntityManager();
        
        $dql = "SELECT d
        FROM JHWEBGestionDocumentalBundle:GdDocumento d
        WHERE d.fechaLlegada BETWEEN :fechaInicial AND :fechaFinal
        ORDER BY d.fechaLlegada ASC";

        $consulta = $em->createQuery($dql);
        $consulta->setParameters(array(
            'fechaInicial' => $fechaInicial,
            'fechaFinal' => $fechaFinal,
        ));

        return $consulta->getResult();
    }
}
