<?php

namespace JHWEB\GestionDocumentalBundle\Repository;

/**
 * GdDocumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GdDocumentoRepository extends \Doctrine\ORM\EntityRepository
{
	//Obtiene el numero maximo de documentos por año
    public function getMaximo($anio)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT MAX(d.consecutivo) AS maximo
            FROM JHWEBGestionDocumentalBundle:GdDocumento d
            WHERE YEAR(d.fechaRegistro) = :ANIO";
        $consulta = $em->createQuery($dql);
        $consulta->setParameter('ANIO', $anio);
        return $consulta->getOneOrNullResult();
    }

	//Obtiene la lista de documentos por peticionario
    public function getByPeticionario($tipoPeticionario, $identificacion = null, $entidadNombre = null, $numeroOficio = null){   
        $em = $this->getEntityManager();

        if ($tipoPeticionario == "Persona") {
        	$dql = "SELECT d
            FROM JHWEBGestionDocumentalBundle:GdDocumento d, AppBundle:Ciudadano c,
            UsuarioBundle:Usuario u
            WHERE d.peticionario = c.id
            AND c.usuario = u.id
            AND u.identificacion = :identificacion";

	        $consulta = $em->createQuery($dql);
	        $consulta->setParameters(array(
	            'identificacion' => $identificacion,
	        ));
        }else{
        	$dql = "SELECT d
            FROM JHWEBGestionDocumentalBundle:GdDocumento d, AppBundle:Ciudadano c
            WHERE d.peticionario = c.id
            AND d.entidadNombre = :entidadNombre
            AND d.numeroOficio = :numeroOficio";

	        $consulta = $em->createQuery($dql);
	        $consulta->setParameters(array(
	            'entidadNombre' => $entidadNombre,
	            'numeroOficio' => $numeroOficio,
	        ));
        }

        return $consulta->getResult();
    }
}
