<?php

namespace JHWEB\GestionDocumentalBundle\Repository;

/**
 * GdMedidaCautelarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GdMedidaCautelarRepository extends \Doctrine\ORM\EntityRepository
{
}
