<?php

namespace JHWEB\GestionDocumentalBundle\Repository;

/**
 * GdRemitenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GdRemitenteRepository extends \Doctrine\ORM\EntityRepository
{
}
