<?php

namespace JHWEB\GestionDocumentalBundle\Repository;

/**
 * GdTrazabilidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GdTrazabilidadRepository extends \Doctrine\ORM\EntityRepository
{
}
