<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * CfgTransportePasajeroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgTransportePasajeroRepository extends \Doctrine\ORM\EntityRepository
{
}
