<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * CfgTransporteEspecialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgTransporteEspecialRepository extends \Doctrine\ORM\EntityRepository
{
}
