<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * SoatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoatRepository extends \Doctrine\ORM\EntityRepository
{
}
