<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * TecnoMecanicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TecnoMecanicaRepository extends \Doctrine\ORM\EntityRepository
{
}
