<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloTpRangoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloTpRangoRepository extends \Doctrine\ORM\EntityRepository
{
}
