<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgSubpartidaArancelariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgSubpartidaArancelariaRepository extends \Doctrine\ORM\EntityRepository
{
}
