<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgClaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgClaseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByModulo($id){
        $em = $this->getEntityManager();

        $dql = "SELECT c
                    FROM JHWEBVehiculoBundle:VhloCfgClase c, JHWEBVehiculoBundle:VhloCfgTipoVehiculo tv, JHWEBConfigBundle:CfgModulo m
                    WHERE c.
                    AND m.id = :id
                    AND tv.modulo = m.id
                    AND c.tipoVehiculo = tv.id
                    AND c.activo = 1";

        $consulta = $em->createQuery($dql);
        $consulta->setParameters(array(
            'id' => $id,
        ));

        return $consulta->getResult();

    }
}
