<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgModalidadTransporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgModalidadTransporteRepository extends \Doctrine\ORM\EntityRepository
{
}
