<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloMaquinariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloMaquinariaRepository extends \Doctrine\ORM\EntityRepository
{
}
