<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgEmpresaGpsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgEmpresaGpsRepository extends \Doctrine\ORM\EntityRepository
{
}
