<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgMotivoCancelacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgMotivoCancelacionRepository extends \Doctrine\ORM\EntityRepository
{
}
