<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloPlacaSedeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloPlacaSedeRepository extends \Doctrine\ORM\EntityRepository
{
}
