<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgLineaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgLineaRepository extends \Doctrine\ORM\EntityRepository
{
}
