<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgCombustibleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgCombustibleRepository extends \Doctrine\ORM\EntityRepository
{
}
