<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloRemolqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloRemolqueRepository extends \Doctrine\ORM\EntityRepository
{
}
