<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloAcreedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloAcreedorRepository extends \Doctrine\ORM\EntityRepository
{
}
