<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloPlacaSedeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloPlacaSedeRepository extends \Doctrine\ORM\EntityRepository
{
    //Obtiene todas las asignaciones por organismo de transito y modulo 
    public function getByOrganismoTransitoAndModulo($idOrganismoTransito, $idModulo)
    {   
        $em = $this->getEntityManager();
        $dql = "SELECT vps
        FROM JHWEBVehiculoBundle:VhloPlacaSede vps,
        JHWEBVehiculoBundle:VhloCfgTipoVehiculo tv
        WHERE vps.tipoVehiculo = tv.id
        AND vps.organismoTransito = :idOrganismoTransito
        AND tv.modulo = :idModulo";
        $consulta = $em->createQuery($dql);
        
        $consulta->setParameters(array(
            'idOrganismoTransito' => $idOrganismoTransito,
            'idModulo' => $idModulo,
        ));

        return $consulta->getResult();
    }
}
