<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgNivelServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgNivelServicioRepository extends \Doctrine\ORM\EntityRepository
{
}
