<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloTpCupoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloTpCupoRepository extends \Doctrine\ORM\EntityRepository
{
}
