<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgOrigenRegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgOrigenRegistroRepository extends \Doctrine\ORM\EntityRepository
{
}
