<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgTipoAlertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgTipoAlertaRepository extends \Doctrine\ORM\EntityRepository
{
}
