<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloPropietarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloPropietarioRepository extends \Doctrine\ORM\EntityRepository
{
}
