<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgCdaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgCdaRepository extends \Doctrine\ORM\EntityRepository
{
}
