<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgTipoVehiculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgTipoVehiculoRepository extends \Doctrine\ORM\EntityRepository
{
}
