<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgClaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgClaseRepository extends \Doctrine\ORM\EntityRepository
{
}
