<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloTpConvenioEmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloTpConvenioEmpresaRepository extends \Doctrine\ORM\EntityRepository
{
}
