<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgLimitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgLimitacionRepository extends \Doctrine\ORM\EntityRepository
{
}
