<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgLimitacionTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgLimitacionTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
