<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgValorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgValorRepository extends \Doctrine\ORM\EntityRepository
{
}
