<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgColorRepository extends \Doctrine\ORM\EntityRepository
{
}
