<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgClaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgClaseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByModulo($idModulo){
        $em = $this->getEntityManager();

        $dql = "SELECT c
        FROM JHWEBVehiculoBundle:VhloCfgClase c, 
        JHWEBVehiculoBundle:VhloCfgTipoVehiculo tv, 
        JHWEBConfigBundle:CfgModulo m
        WHERE m.id = :idModulo
        AND tv.modulo = m.id
        AND c.tipoVehiculo = tv.id
        AND c.activo = true";

        $consulta = $em->createQuery($dql);
        $consulta->setParameters(array(
            'idModulo' => $idModulo
        ));

        return $consulta->getResult();
    }
}
