<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloActaTraspasoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloActaTraspasoRepository extends \Doctrine\ORM\EntityRepository
{
}
