<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloTpConvenioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloTpConvenioRepository extends \Doctrine\ORM\EntityRepository
{
}
