<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloSoatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloSoatRepository extends \Doctrine\ORM\EntityRepository
{
}
