<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgTipoMaquinariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgTipoMaquinariaRepository extends \Doctrine\ORM\EntityRepository
{
}
