<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgTransporteEspecialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgTransporteEspecialRepository extends \Doctrine\ORM\EntityRepository
{
}
