<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgPlacaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgPlacaRepository extends \Doctrine\ORM\EntityRepository
{
}
