<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgTransportePasajeroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgTransportePasajeroRepository extends \Doctrine\ORM\EntityRepository
{
}
