<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgServicioRepository extends \Doctrine\ORM\EntityRepository
{
}
