<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgCondicionIngresoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgCondicionIngresoRepository extends \Doctrine\ORM\EntityRepository
{
}
