<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloTpAsignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloTpAsignacionRepository extends \Doctrine\ORM\EntityRepository
{
}
