<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgLimitacionCausalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgLimitacionCausalRepository extends \Doctrine\ORM\EntityRepository
{
}
