<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloTpTarjetaOperacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloTpTarjetaOperacionRepository extends \Doctrine\ORM\EntityRepository
{
}
