<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloRestriccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloRestriccionRepository extends \Doctrine\ORM\EntityRepository
{
}
