<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgLimitacionTipoProcesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgLimitacionTipoProcesoRepository extends \Doctrine\ORM\EntityRepository
{
}
