<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloDevolucionRadicadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloDevolucionRadicadoRepository extends \Doctrine\ORM\EntityRepository
{
}
