<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloPropietarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloPropietarioRepository extends \Doctrine\ORM\EntityRepository
{
    //Obtiene todos los propietario de los vehiculos del módulo RNA entre fechas para creación de archivo plano
    public function getByFechasForFile($idOrganismoTransito, $idModulo, $fechaInicial, $fechaFinal)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT vp

        FROM JHWEBVehiculoBundle:VhloPropietario vp, 
            JHWEBVehiculoBundle:VhloVehiculo v,
            JHWEBVehiculoBundle:VhloCfgClase vcc,
            JHWEBVehiculoBundle:VhloCfgTipoVehiculo vctv,
            JHWEBConfigBundle:CfgModulo m

            WHERE v.organismoTransito = :idOrganismoTransito
            AND v.clase = vcc.id
            AND vcc.tipoVehiculo = vctv.id
            AND vctv.modulo = :idModulo
            AND vp.activo = 1
            AND v.activo = 1
            AND vp.fechaInicial BETWEEN :fechaInicial AND :fechaFinal";

        $consulta = $em->createQuery($dql);

        $consulta->setParameters(array(
            'fechaInicial' => $fechaInicial,
            'fechaFinal' => $fechaFinal,
            'idOrganismoTransito' => $idOrganismoTransito,
            'idModulo' => $idModulo,
        ));
        
        return $consulta->getResult();
    }
}
