<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgCarroceriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgCarroceriaRepository extends \Doctrine\ORM\EntityRepository
{
}
