<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgTipoCabinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgTipoCabinaRepository extends \Doctrine\ORM\EntityRepository
{
}
