<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgMarcaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgMarcaRepository extends \Doctrine\ORM\EntityRepository
{
}
