<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgTipoVehiculoClaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgTipoVehiculoClaseRepository extends \Doctrine\ORM\EntityRepository
{
}
