<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloCfgRadioAccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloCfgRadioAccionRepository extends \Doctrine\ORM\EntityRepository
{
}
