<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhloTecnoMecanicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhloTecnoMecanicaRepository extends \Doctrine\ORM\EntityRepository
{
}
