<?php

namespace JHWEB\VehiculoBundle\Repository;

/**
 * VhoActaTraspasoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhoActaTraspasoRepository extends \Doctrine\ORM\EntityRepository
{
}
