<?php

namespace JHWEB\ConfigBundle\Repository;

/**
 * CfgAuditoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgAuditoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
