<?php

namespace JHWEB\ConfigBundle\Repository;

/**
 * CfgAdmFormatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgAdmFormatoRepository extends \Doctrine\ORM\EntityRepository
{
}
