<?php

namespace JHWEB\ConfigBundle\Repository;

/**
 * CfgAdmFormatoTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgAdmFormatoTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
