<?php

namespace JHWEB\ConfigBundle\Repository;

/**
 * CfgClaveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgClaveRepository extends \Doctrine\ORM\EntityRepository
{
}
