<?php

namespace JHWEB\ConfigBundle\Repository;

/**
 * CfgDepartamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgDepartamentoRepository extends \Doctrine\ORM\EntityRepository
{
}
