<?php

namespace JHWEB\ConfigBundle\Repository;

/**
 * CfgEntidadJudicialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgEntidadJudicialRepository extends \Doctrine\ORM\EntityRepository
{
}
