<?php

namespace JHWEB\ConfigBundle\Repository;

/**
 * CfgEmpresaServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgEmpresaServicioRepository extends \Doctrine\ORM\EntityRepository
{
}
