<?php

namespace JHWEB\ConfigBundle\Repository;

/**
 * CfgMunicipioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgMunicipioRepository extends \Doctrine\ORM\EntityRepository
{
}
