<?php

namespace JHWEB\ConfigBundle\Repository;

/**
 * CfgModuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgModuloRepository extends \Doctrine\ORM\EntityRepository
{
}
