<?php

namespace JHWEB\ConfigBundle\Repository;

/**
 * CfgOrganismoTransitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgOrganismoTransitoRepository extends \Doctrine\ORM\EntityRepository
{
}
