<?php

namespace JHWEB\ConfigBundle\Repository;

/**
 * CfgPropietarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgPropietarioRepository extends \Doctrine\ORM\EntityRepository
{
}
