<?php

namespace JHWEB\ConfigBundle\Repository;

/**
 * CfgPaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgPaisRepository extends \Doctrine\ORM\EntityRepository
{
}
