<?php

namespace JHWEB\ConfigBundle\Repository;

/**
 * CfgSvConectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgSvConectorRepository extends \Doctrine\ORM\EntityRepository
{
}
