<?php

namespace JHWEB\ConfigBundle\Repository;

/**
 * CfgSvUnidadMedidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgSvUnidadMedidaRepository extends \Doctrine\ORM\EntityRepository
{
}
