<?php

namespace JHWEB\ConfigBundle\Repository;

/**
 * CfgSvSenialEstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgSvSenialEstadoRepository extends \Doctrine\ORM\EntityRepository
{
}
