<?php

namespace JHWEB\ConfigBundle\Repository;

/**
 * CfgSvSenialTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgSvSenialTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
