<?php

namespace JHWEB\ConfigBundle\Repository;

/**
 * CfgSvSenialDestinoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgSvSenialDestinoRepository extends \Doctrine\ORM\EntityRepository
{
}
