<?php

namespace JHWEB\ConfigBundle\Repository;

/**
 * CfgSvSenialColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfgSvSenialColorRepository extends \Doctrine\ORM\EntityRepository
{
}
