<?php

namespace Repository\UsuarioBundle\Repository;

/**
 * UserCfgMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCfgMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
