<?php

namespace Repository\UsuarioBundle\Repository;

/**
 * UserCfgPermisoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCfgPermisoRepository extends \Doctrine\ORM\EntityRepository
{
}
